#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Guy Shtainer
"""tools/gb_claims.py -- mechanically verify a shot's caption against its own pixels
(BACKLOG #184).

WHY THIS EXISTS
----------------
Three rounds and ~900k tokens went on captions describing frames nobody had looked at
(BACKLOG #198). A caption is a CLAIM about pixels; this module turns "the frame shows
X" into a check a machine can run: render the string X the same way PokeDNA's own UI
code renders it, then search the frame PNG for a pixel-exact match. No OCR, no
ML -- exact bitmap search against PokeDNA's own two font sources.

TWO FONT SOURCES, TWO RENDER MODES
-----------------------------------
PokeDNA draws text through exactly two code paths (source/ui.c):

  ui_ptext()/ui_ptext_fit()/... -- OUR OWN proportional 5x7 face, `ui_font_bits`
    (source/ui_font.c, GENERATED by tools/gen_font.py, not ROM-derived). Row bytes,
    bit 0 = LEFTMOST pixel (ui_font.c's own header comment; verified against the
    blitter below). Advance per glyph is `ui_font_w[i]` = ink width + 1px gap
    (ui.c:8's comment, matches PADV()/ui_ptext's `x += PADV(c)` at ui.c:357).
    render(text, proportional=True) reproduces this.

  ui_text()/ui_text_sel() -- tonc's OWN "sys8Font" via tte_set_pos()+tte_write()
    (ui.c:75-86). This is NOT ui_font_bits -- it is a separate, fixed-width 8x8
    bitmap baked into libtonc (declared `extern const TFont sys8Font` in
    tonc_tte.h:339, documented there as "FWF 8x8@1" -- Fixed-Width Font, 8 pixels
    wide, 1 bit per pixel, space(0x20)..127, the identical 96-glyph range
    ui_font_bits covers). libtonc ships this font only as compiled object code
    (toncfont.o inside lib/libtonc.a's .rodata, symbol `toncfontTiles`) -- there
    is no C source in the devkitPro tree to parse the way ui_font.c is parsed
    below. TONC_SYS8_BITS is that SAME 768-byte table (96 glyphs x 8 rows),
    extracted once with `arm-none-eabi-objcopy -O binary --only-section=.rodata`
    against /opt/devkitpro/libtonc/lib/libtonc.a's toncfont.o member and frozen
    here as a hex literal -- it is libtonc's own font data (already linked into
    every PokeDNA build; WTFPL-licensed upstream, not ROM/game-derived), read
    straight out of the toolchain PokeDNA already builds with, not out of any
    Nintendo ROM. Bit order is the same convention tonc documents for its own
    sys8 (ui_font.c's header comment cites it directly: "same order as tonc's
    sys8"). Advance is FIXED at 8 px (no per-glyph width table for this font --
    TFont.widths is NULL for sys8Font, so tte falls back to `font->charW`, tonc's
    own 8px cell -- tonc_tte.h's TTE_CHAR_VARS macro, `font->widths ? ... :
    font->charW`).
    render(text, proportional=False) reproduces this.

  render(text, proportional=None) is not a third mode -- callers needing "try
  both, whichever matches" call find() with proportional=None (below), which
  tries both renderers rather than guessing.

RENDER
------
render() returns an (8, total_width) bool numpy array: True = ink pixel. Each
glyph is placed at consecutive columns; the inter-glyph GAP is included in the
array as False columns (both the ink test on that glyph's own trailing gap
columns AND the leading columns before the next glyph read 0) -- so a caller
searching for this exact bitmap in a frame requires the gap pixels to be
NON-ink too, not merely "don't care". This is deliberate (see find()'s
docstring) -- it is what "the frame shows this text" should mean pixel for
pixel, given both PokeDNA fonts never draw anything into the gap.

FIND
----
find(frame_png, text, proportional=None) treats the frame as a stack of binary
planes, one per distinct colour present, and slides the rendered mask over
each plane with numpy.lib.stride_tricks.sliding_window_view, looking for an
EXACT match (every ink pixel of the mask equals that colour, every
gap/background pixel of the mask's footprint does NOT). Text colour is not
known a priori (menus, footers, selected-row inverse video, and the HOF
crystal-card panel all use different ink colours) -- trying every distinct
colour in the frame is the only caller-agnostic way to find it. A
drop-shadow/outline variant (ui_ptext_shadow, ui.c:439-441, draws the SAME
string twice at a 1px offset in two different colours) still matches on its
own main-ink colour plane: the shadow copy is a different colour, so it is
invisible on the main colour's binary plane except where it happens to
overlap real background pixels of that colour, which the exact-gap-match
requirement then rejects same as any other stray ink.

A normal GBA UI capture is indexed 15-bit colour and never has more than a
few dozen distinct RGB values, but a sprite/gameplay frame (icons, box art,
dithered gradients) can legitimately exceed 256 -- BACKLOG #214. Raising in
that case turned "this claim doesn't hold on this kind of frame" into a
crash that aborted the whole runner instead of a normal `[CLAIM FAILED]`.
find() therefore never raises on colour count: it bounds the search to the
MAX_COLOURS_SCANNED most FREQUENT colours in the frame (by pixel count).
Rendered text is always a solid run of many same-coloured ink pixels (a
"text-sized run"), so its ink colour is high-frequency even against a busy
sprite frame's many low-frequency (often singleton) art colours; this is a
bounded per-colour search over the most-frequent colours, not quantisation,
so it never distorts the exact bitmap match. When the frame has
<=MAX_COLOURS_SCANNED colours this is exactly the old exhaustive search
(every colour is "most frequent" by definition); above the cap it is a
best-effort search that can miss a low-frequency ink colour, which is
reported as an ordinary empty result (claim failure), never an exception.
"""
from __future__ import annotations

import re
from pathlib import Path

import numpy as np
from numpy.lib.stride_tricks import sliding_window_view
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
UI_FONT_C = ROOT / "source" / "ui_font.c"

# Bound on find()'s per-colour plane search (module docstring, "FIND"): above
# this many distinct colours in a frame, only the this-many MOST FREQUENT
# colours are searched -- never a crash, see BACKLOG #214.
MAX_COLOURS_SCANNED = 256

FIRST_CP = 0x20   # space -- ui_font.c's own header comment: "96 glyphs, ASCII 32..127"
NUM_GLYPHS = 96
GLYPH_ROWS = 8

# ---------------------------------------------------------------------------
# tonc's sys8Font (ui_text()/tte_write() path) -- see the module docstring for
# provenance. 96 glyphs x 8 row-bytes, same space(0x20)..127 range and bit
# order (bit 0 = leftmost pixel) as our own ui_font_bits.
# ---------------------------------------------------------------------------
TONC_SYS8_HEX = (
    "00000000000000001818181818001800363600000000000036367f367f363600"
    "187c063c603e18000066351b6c5633001c36166e3b73de0018180c0000000000"
    "30180c0c0c1830000c18303030180c0000663cff3c6600000018187e18180000"
    "000000000018180c0000007e000000000000000000181800c06030180c060300"
    "3c66767e6e663c00181c1e18181818003c666030180c7e003c66603860663c00"
    "383c36337f3030007e063e6060663c00380c063e66663c007e60603018181800"
    "3c66663c66663c003c66667c60301c000018180000181800001818000018180c"
    "006018061860000000007e007e00000000061860180600003c66603018001800"
    "3c665a5a7a063c003c66667e666666003e66663e66663e00780c0606060c7800"
    "1e36666666361e007e06061e06067e007e06061e060606003c66067666667c00"
    "6666667e666666003c18181818183c006060606060663c0063331b0f1b336300"
    "0606060606067e0063777f6b6363630063676f7b736363003c66666666663c00"
    "3e66663e060606001e333333333b7e003e66663e366666003c660e3c70663c00"
    "7e181818181818006666666666663c00666666663c3c18006363636b7f776300"
    "c3663c183c66c300c3663c18181818007f30180c06037f003c0c0c0c0c0c3c00"
    "03060c183060c0003c30303030303c00183c6600000000000000000000003f00"
    "181830000000000000003c607c667c0006063e6666663e0000003c0606063c00"
    "60607c6666667c0000003c667e063c00380c3e0c0c0c0c0000007c66667c603c"
    "06063e66666666001800181818183000300030303030301e060666361e366600"
    "18181818181830000000377f6b63630000003e666666660000003c6666663c00"
    "00003e66663e060600007c66667c606000003e660606060000003c063c603e00"
    "0c0c3e0c0c0c38000000666666667c0000006666663c1800000063636b7f3600"
    "000063361c36630000006666663c180c00007e30180c7e003018180c18183000"
    "18181818181818000c18183018180c00006e3b00000000000000000000000000"
)


def _load_tonc_bits() -> bytes:
    """The authoritative bytes: read straight from a freshly re-extracted copy
    of libtonc's toncfont.o .rodata section when the toolchain is available (so
    a stale hex literal can never silently drift from the linked font), else
    fall back to the frozen TONC_SYS8_HEX literal above (offline / no
    devkitARM -- host tests must still run)."""
    import shutil
    import subprocess
    import tempfile

    libtonc_a = Path("/opt/devkitpro/libtonc/lib/libtonc.a")
    objcopy = shutil.which("arm-none-eabi-objcopy") or "/opt/devkitpro/devkitARM/bin/arm-none-eabi-objcopy"
    ar = shutil.which("arm-none-eabi-ar") or "/opt/devkitpro/devkitARM/bin/arm-none-eabi-ar"
    if libtonc_a.is_file() and Path(objcopy).exists() and Path(ar).exists():
        try:
            with tempfile.TemporaryDirectory() as td:
                tdp = Path(td)
                subprocess.run([ar, "x", str(libtonc_a), "toncfont.o"], cwd=tdp,
                                check=True, capture_output=True)
                subprocess.run([objcopy, "-O", "binary", "--only-section=.rodata",
                                 "toncfont.o", "sys8font.bin"], cwd=tdp,
                                check=True, capture_output=True)
                data = (tdp / "sys8font.bin").read_bytes()
                if len(data) == NUM_GLYPHS * GLYPH_ROWS:
                    return data
        except (OSError, subprocess.CalledProcessError, AssertionError):
            pass  # no toolchain / no objcopy here: fall through to the frozen literal
    return bytes.fromhex(TONC_SYS8_HEX)


TONC_SYS8_BITS: bytes = _load_tonc_bits()
assert len(TONC_SYS8_BITS) == NUM_GLYPHS * GLYPH_ROWS, (
    f"TONC_SYS8_BITS: expected {NUM_GLYPHS * GLYPH_ROWS} bytes, got {len(TONC_SYS8_BITS)}")


# ---------------------------------------------------------------------------
# Parse source/ui_font.c's ui_font_bits[]/ui_font_w[] -- never hand-copy these,
# the generated file (tools/gen_font.py) is the single source of truth and a
# stale hand copy here would silently drift the moment the font is regenerated.
# ---------------------------------------------------------------------------
def _parse_ui_font_c(path: Path = UI_FONT_C) -> tuple[list[int], list[int]]:
    text = path.read_text(encoding="utf-8")

    m_bits = re.search(r"ui_font_bits\[96\s*\*\s*8\]\s*=\s*\{(.*?)\};", text, re.DOTALL)
    if not m_bits:
        raise ValueError(f"{path}: could not find the ui_font_bits[96 * 8] array literal")
    bit_tokens = re.findall(r"0[xX][0-9A-Fa-f]{1,2}", m_bits.group(1))
    if len(bit_tokens) != NUM_GLYPHS * GLYPH_ROWS:
        raise ValueError(f"{path}: expected {NUM_GLYPHS * GLYPH_ROWS} ui_font_bits bytes, "
                          f"found {len(bit_tokens)}")
    bits = [int(t, 16) for t in bit_tokens]

    m_w = re.search(r"ui_font_w\[96\]\s*=\s*\{(.*?)\};", text, re.DOTALL)
    if not m_w:
        raise ValueError(f"{path}: could not find the ui_font_w[96] array literal")
    # Strip comments first so a stray number inside a /* ... */ block is never
    # mistaken for an advance value.
    w_body = re.sub(r"/\*.*?\*/", "", m_w.group(1), flags=re.DOTALL)
    w_tokens = re.findall(r"\d+", w_body)
    if len(w_tokens) != NUM_GLYPHS:
        raise ValueError(f"{path}: expected {NUM_GLYPHS} ui_font_w values, found {len(w_tokens)}")
    widths = [int(t) for t in w_tokens]

    return bits, widths


UI_FONT_BITS, UI_FONT_W = _parse_ui_font_c()


def _glyph_rows(bits: list[int], codepoint: int) -> list[int]:
    if not (FIRST_CP <= codepoint < FIRST_CP + NUM_GLYPHS):
        raise ValueError(f"codepoint {codepoint!r} (U+{codepoint:04X}) is outside the "
                          f"font's range [{FIRST_CP:#04x}, {FIRST_CP + NUM_GLYPHS - 1:#04x}]")
    base = (codepoint - FIRST_CP) * GLYPH_ROWS
    return bits[base:base + GLYPH_ROWS]


def render(text: str, proportional: bool = True) -> np.ndarray:
    """Render `text` the way PokeDNA's own ui_ptext() (proportional=True) or
    ui_text()/tte_write() (proportional=False) would draw it, as an
    (8, total_width) bool array (True = ink). The inter-glyph gap is baked in
    as False columns for both modes -- see the module docstring."""
    if not text:
        return np.zeros((GLYPH_ROWS, 0), dtype=bool)

    if proportional:
        bits, widths = UI_FONT_BITS, UI_FONT_W
    else:
        bits, widths = list(TONC_SYS8_BITS), [8] * NUM_GLYPHS

    total_w = 0
    glyphs = []
    for ch in text:
        cp = ord(ch)
        rows = _glyph_rows(bits, cp)
        width = widths[cp - FIRST_CP]
        glyphs.append((rows, width))
        total_w += width

    mask = np.zeros((GLYPH_ROWS, total_w), dtype=bool)
    x = 0
    for rows, width in glyphs:
        for r, byte in enumerate(rows):
            for col in range(width):
                if (byte >> col) & 1:
                    mask[r, x + col] = True
        x += width
    return mask


def find(frame_png: str | Path | Image.Image | np.ndarray, text: str,
         proportional: bool | None = None) -> list[tuple[int, int, tuple[int, int, int]]]:
    """Search `frame_png` (a path or an already-loaded PIL Image / ndarray) for an
    EXACT pixel match of render(text, proportional). proportional=None tries
    BOTH renderers (ui_ptext's and ui_text's fonts) since the caller does not
    know a priori which one drew a given piece of UI text.

    Returns a list of (x, y, colour) hits -- (x, y) is the top-left corner of
    the match, colour is the (R, G, B) the glyph was drawn in on that frame.
    Empty list = not found."""
    if isinstance(frame_png, np.ndarray):
        arr = frame_png
    else:
        img = frame_png if isinstance(frame_png, Image.Image) else Image.open(frame_png)
        arr = np.asarray(img.convert("RGB"))

    modes = [True, False] if proportional is None else [proportional]
    hits: list[tuple[int, int, tuple[int, int, int]]] = []
    for prop in modes:
        mask = render(text, proportional=prop)
        h, w = mask.shape
        if h == 0 or w == 0 or h > arr.shape[0] or w > arr.shape[1]:
            continue
        colours, counts = np.unique(arr.reshape(-1, arr.shape[-1]), axis=0, return_counts=True)
        if len(colours) > MAX_COLOURS_SCANNED:
            # Bounded fallback for a >256-colour frame (a sprite/gameplay screen,
            # not a UI render) -- see the module docstring's FIND section and
            # MAX_COLOURS_SCANNED above. Never raise: search only the most
            # frequent colours and let a miss fall out as a normal empty result.
            order = np.argsort(-counts)[:MAX_COLOURS_SCANNED]
            colours = colours[order]
        for colour in colours:
            plane = np.all(arr == colour, axis=-1)
            windows = sliding_window_view(plane, (h, w))
            matches = np.all(windows == mask, axis=(2, 3))
            ys, xs = np.nonzero(matches)
            for y, x in zip(ys.tolist(), xs.tolist()):
                hits.append((x, y, tuple(int(c) for c in colour)))
    return hits


def check(frame_png: str | Path | Image.Image | np.ndarray,
          claim: str | list[str] | None = None, claim_absent: str | list[str] | None = None,
          proportional: bool | None = None) -> list[str]:
    """The shared gate used by both Session.shot() (live, BACKLOG #184 item 2) and
    --selftest-captions's offline re-check (item 2's extension): returns a list
    of human-readable failure strings (empty = every claim/claim_absent held).
    `claim`/`claim_absent` are each a string or a list of strings (None = no
    check of that kind)."""
    def as_list(v):
        if v is None:
            return []
        return [v] if isinstance(v, str) else list(v)

    failures: list[str] = []
    for text in as_list(claim):
        if not find(frame_png, text, proportional=proportional):
            failures.append(f"'{text}' not on frame")
    for text in as_list(claim_absent):
        if find(frame_png, text, proportional=proportional):
            failures.append(f"'{text}' unexpectedly ON frame (claim_absent)")
    return failures
