#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Guy Shtainer
"""tools/gb_claims.py -- mechanically verify a shot's caption against its own pixels
(BACKLOG #184).

WHY THIS EXISTS
----------------
Three rounds and ~900k tokens went on captions describing frames nobody had looked at
(BACKLOG #198). A caption is a CLAIM about pixels; this module turns "the frame shows
X" into a check a machine can run: render the string X the same way PokeDNA's own UI
code renders it, then search the frame PNG for a pixel-exact match. No OCR, no
ML -- exact bitmap search against PokeDNA's own two font sources.

TWO FONT SOURCES, TWO RENDER MODES
-----------------------------------
PokeDNA draws text through exactly two code paths (source/ui.c):

  ui_ptext()/ui_ptext_fit()/... -- OUR OWN proportional 5x7 face, `ui_font_bits`
    (source/ui_font.c, GENERATED by tools/gen_font.py, not ROM-derived). Row bytes,
    bit 0 = LEFTMOST pixel (ui_font.c's own header comment; verified against the
    blitter below). Advance per glyph is `ui_font_w[i]` = ink width + 1px gap
    (ui.c:8's comment, matches PADV()/ui_ptext's `x += PADV(c)` at ui.c:357).
    render(text, proportional=True) reproduces this.

  ui_text()/ui_text_sel() -- tonc's OWN "sys8Font" via tte_set_pos()+tte_write()
    (ui.c:75-86). This is NOT ui_font_bits -- it is a separate, fixed-width 8x8
    bitmap baked into libtonc (declared `extern const TFont sys8Font` in
    tonc_tte.h:339, documented there as "FWF 8x8@1" -- Fixed-Width Font, 8 pixels
    wide, 1 bit per pixel, space(0x20)..127, the identical 96-glyph range
    ui_font_bits covers). libtonc ships this font only as compiled object code
    (toncfont.o inside lib/libtonc.a's .rodata, symbol `toncfontTiles`) -- there
    is no C source in the devkitPro tree to parse the way ui_font.c is parsed
    below. TONC_SYS8_BITS is that SAME 768-byte table (96 glyphs x 8 rows),
    extracted once with `arm-none-eabi-objcopy -O binary --only-section=.rodata`
    against /opt/devkitpro/libtonc/lib/libtonc.a's toncfont.o member and frozen
    here as a hex literal -- it is libtonc's own font data (already linked into
    every PokeDNA build; WTFPL-licensed upstream, not ROM/game-derived), read
    straight out of the toolchain PokeDNA already builds with, not out of any
    Nintendo ROM. Bit order is the same convention tonc documents for its own
    sys8 (ui_font.c's header comment cites it directly: "same order as tonc's
    sys8"). Advance is FIXED at 8 px (no per-glyph width table for this font --
    TFont.widths is NULL for sys8Font, so tte falls back to `font->charW`, tonc's
    own 8px cell -- tonc_tte.h's TTE_CHAR_VARS macro, `font->widths ? ... :
    font->charW`).
    render(text, proportional=False) reproduces this.

  render(text, proportional=None) is not a third mode -- callers needing "try
  both, whichever matches" call find() with proportional=None (below), which
  tries both renderers rather than guessing.

RENDER
------
render() returns an (8, total_width) bool numpy array: True = ink pixel. Each
glyph is placed at consecutive columns; the inter-glyph GAP is included in the
array as False columns (both the ink test on that glyph's own trailing gap
columns AND the leading columns before the next glyph read 0) -- so a caller
searching for this exact bitmap in a frame requires the gap pixels to be
NON-ink too, not merely "don't care". This is deliberate (see find()'s
docstring) -- it is what "the frame shows this text" should mean pixel for
pixel, given both PokeDNA fonts never draw anything into the gap.

FIND
----
find(frame_png, text, proportional=None) treats the frame as a stack of binary
planes, one per distinct colour present, and slides the rendered mask over
each plane with numpy.lib.stride_tricks.sliding_window_view, looking for an
EXACT match (every ink pixel of the mask equals that colour, every
gap/background pixel of the mask's footprint does NOT). Text colour is not
known a priori (menus, footers, selected-row inverse video, and the HOF
crystal-card panel all use different ink colours) -- trying every distinct
colour in the frame is the only caller-agnostic way to find it. A
drop-shadow/outline variant (ui_ptext_shadow, ui.c:439-441, draws the SAME
string twice at a 1px offset in two different colours) still matches on its
own main-ink colour plane: the shadow copy is a different colour, so it is
invisible on the main colour's binary plane except where it happens to
overlap real background pixels of that colour, which the exact-gap-match
requirement then rejects same as any other stray ink.

A normal GBA UI capture is indexed 15-bit colour and never has more than a
few dozen distinct RGB values, but a sprite/gameplay frame (icons, box art,
dithered gradients) can legitimately exceed 256 -- BACKLOG #214. Raising in
that case turned "this claim doesn't hold on this kind of frame" into a
crash that aborted the whole runner instead of a normal `[CLAIM FAILED]`.
find() therefore never raises on colour count: it bounds the search to the
MAX_COLOURS_SCANNED most FREQUENT colours in the frame (by pixel count).
Rendered text is always a solid run of many same-coloured ink pixels (a
"text-sized run"), so its ink colour is high-frequency even against a busy
sprite frame's many low-frequency (often singleton) art colours; this is a
bounded per-colour search over the most-frequent colours, not quantisation,
so it never distorts the exact bitmap match. When the frame has
<=MAX_COLOURS_SCANNED colours this is exactly the old exhaustive search
(every colour is "most frequent" by definition); above the cap it is a
best-effort search that can miss a low-frequency ink colour, which is
reported as an ordinary empty result (claim failure), never an exception.
"""
from __future__ import annotations

import re
import shutil
import subprocess
import tempfile
from pathlib import Path

import numpy as np
from numpy.lib.stride_tricks import sliding_window_view
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
UI_FONT_C = ROOT / "source" / "ui_font.c"

# Bound on find()'s per-colour plane search (module docstring, "FIND"): above
# this many distinct colours in a frame, only the this-many MOST FREQUENT
# colours are searched -- never a crash, see BACKLOG #214.
MAX_COLOURS_SCANNED = 256

FIRST_CP = 0x20   # space -- ui_font.c's own header comment: "96 glyphs, ASCII 32..127"
NUM_GLYPHS = 96
GLYPH_ROWS = 8

# ---------------------------------------------------------------------------
# tonc's sys8Font (ui_text()/tte_write() path) -- see the module docstring for
# provenance. 96 glyphs x 8 row-bytes, same space(0x20)..127 range and bit
# order (bit 0 = leftmost pixel) as our own ui_font_bits.
# ---------------------------------------------------------------------------
TONC_SYS8_HEX = (
    "00000000000000001818181818001800363600000000000036367f367f363600"
    "187c063c603e18000066351b6c5633001c36166e3b73de0018180c0000000000"
    "30180c0c0c1830000c18303030180c0000663cff3c6600000018187e18180000"
    "000000000018180c0000007e000000000000000000181800c06030180c060300"
    "3c66767e6e663c00181c1e18181818003c666030180c7e003c66603860663c00"
    "383c36337f3030007e063e6060663c00380c063e66663c007e60603018181800"
    "3c66663c66663c003c66667c60301c000018180000181800001818000018180c"
    "006018061860000000007e007e00000000061860180600003c66603018001800"
    "3c665a5a7a063c003c66667e666666003e66663e66663e00780c0606060c7800"
    "1e36666666361e007e06061e06067e007e06061e060606003c66067666667c00"
    "6666667e666666003c18181818183c006060606060663c0063331b0f1b336300"
    "0606060606067e0063777f6b6363630063676f7b736363003c66666666663c00"
    "3e66663e060606001e333333333b7e003e66663e366666003c660e3c70663c00"
    "7e181818181818006666666666663c00666666663c3c18006363636b7f776300"
    "c3663c183c66c300c3663c18181818007f30180c06037f003c0c0c0c0c0c3c00"
    "03060c183060c0003c30303030303c00183c6600000000000000000000003f00"
    "181830000000000000003c607c667c0006063e6666663e0000003c0606063c00"
    "60607c6666667c0000003c667e063c00380c3e0c0c0c0c0000007c66667c603c"
    "06063e66666666001800181818183000300030303030301e060666361e366600"
    "18181818181830000000377f6b63630000003e666666660000003c6666663c00"
    "00003e66663e060600007c66667c606000003e660606060000003c063c603e00"
    "0c0c3e0c0c0c38000000666666667c0000006666663c1800000063636b7f3600"
    "000063361c36630000006666663c180c00007e30180c7e003018180c18183000"
    "18181818181818000c18183018180c00006e3b00000000000000000000000000"
)


def _load_tonc_bits() -> bytes:
    """The authoritative bytes: read straight from a freshly re-extracted copy
    of libtonc's toncfont.o .rodata section when the toolchain is available (so
    a stale hex literal can never silently drift from the linked font), else
    fall back to the frozen TONC_SYS8_HEX literal above (offline / no
    devkitARM -- host tests must still run)."""
    import shutil
    import subprocess
    import tempfile

    libtonc_a = Path("/opt/devkitpro/libtonc/lib/libtonc.a")
    objcopy = shutil.which("arm-none-eabi-objcopy") or "/opt/devkitpro/devkitARM/bin/arm-none-eabi-objcopy"
    ar = shutil.which("arm-none-eabi-ar") or "/opt/devkitpro/devkitARM/bin/arm-none-eabi-ar"
    if libtonc_a.is_file() and Path(objcopy).exists() and Path(ar).exists():
        try:
            with tempfile.TemporaryDirectory() as td:
                tdp = Path(td)
                subprocess.run([ar, "x", str(libtonc_a), "toncfont.o"], cwd=tdp,
                                check=True, capture_output=True)
                subprocess.run([objcopy, "-O", "binary", "--only-section=.rodata",
                                 "toncfont.o", "sys8font.bin"], cwd=tdp,
                                check=True, capture_output=True)
                data = (tdp / "sys8font.bin").read_bytes()
                if len(data) == NUM_GLYPHS * GLYPH_ROWS:
                    return data
        except (OSError, subprocess.CalledProcessError, AssertionError):
            pass  # no toolchain / no objcopy here: fall through to the frozen literal
    return bytes.fromhex(TONC_SYS8_HEX)


TONC_SYS8_BITS: bytes = _load_tonc_bits()
assert len(TONC_SYS8_BITS) == NUM_GLYPHS * GLYPH_ROWS, (
    f"TONC_SYS8_BITS: expected {NUM_GLYPHS * GLYPH_ROWS} bytes, got {len(TONC_SYS8_BITS)}")


# ---------------------------------------------------------------------------
# Parse source/ui_font.c's ui_font_bits[]/ui_font_w[] -- never hand-copy these,
# the generated file (tools/gen_font.py) is the single source of truth and a
# stale hand copy here would silently drift the moment the font is regenerated.
# ---------------------------------------------------------------------------
def _parse_ui_font_c(path: Path = UI_FONT_C) -> tuple[list[int], list[int]]:
    text = path.read_text(encoding="utf-8")

    m_bits = re.search(r"ui_font_bits\[96\s*\*\s*8\]\s*=\s*\{(.*?)\};", text, re.DOTALL)
    if not m_bits:
        raise ValueError(f"{path}: could not find the ui_font_bits[96 * 8] array literal")
    bit_tokens = re.findall(r"0[xX][0-9A-Fa-f]{1,2}", m_bits.group(1))
    if len(bit_tokens) != NUM_GLYPHS * GLYPH_ROWS:
        raise ValueError(f"{path}: expected {NUM_GLYPHS * GLYPH_ROWS} ui_font_bits bytes, "
                          f"found {len(bit_tokens)}")
    bits = [int(t, 16) for t in bit_tokens]

    m_w = re.search(r"ui_font_w\[96\]\s*=\s*\{(.*?)\};", text, re.DOTALL)
    if not m_w:
        raise ValueError(f"{path}: could not find the ui_font_w[96] array literal")
    # Strip comments first so a stray number inside a /* ... */ block is never
    # mistaken for an advance value.
    w_body = re.sub(r"/\*.*?\*/", "", m_w.group(1), flags=re.DOTALL)
    w_tokens = re.findall(r"\d+", w_body)
    if len(w_tokens) != NUM_GLYPHS:
        raise ValueError(f"{path}: expected {NUM_GLYPHS} ui_font_w values, found {len(w_tokens)}")
    widths = [int(t) for t in w_tokens]

    return bits, widths


UI_FONT_BITS, UI_FONT_W = _parse_ui_font_c()


def _glyph_rows(bits: list[int], codepoint: int) -> list[int]:
    if not (FIRST_CP <= codepoint < FIRST_CP + NUM_GLYPHS):
        raise ValueError(f"codepoint {codepoint!r} (U+{codepoint:04X}) is outside the "
                          f"font's range [{FIRST_CP:#04x}, {FIRST_CP + NUM_GLYPHS - 1:#04x}]")
    base = (codepoint - FIRST_CP) * GLYPH_ROWS
    return bits[base:base + GLYPH_ROWS]


def render(text: str, proportional: bool = True) -> np.ndarray:
    """Render `text` the way PokeDNA's own ui_ptext() (proportional=True) or
    ui_text()/tte_write() (proportional=False) would draw it, as an
    (8, total_width) bool array (True = ink). The inter-glyph gap is baked in
    as False columns for both modes -- see the module docstring."""
    if not text:
        return np.zeros((GLYPH_ROWS, 0), dtype=bool)

    if proportional:
        bits, widths = UI_FONT_BITS, UI_FONT_W
    else:
        bits, widths = list(TONC_SYS8_BITS), [8] * NUM_GLYPHS

    total_w = 0
    glyphs = []
    for ch in text:
        cp = ord(ch)
        rows = _glyph_rows(bits, cp)
        width = widths[cp - FIRST_CP]
        glyphs.append((rows, width))
        total_w += width

    mask = np.zeros((GLYPH_ROWS, total_w), dtype=bool)
    x = 0
    for rows, width in glyphs:
        for r, byte in enumerate(rows):
            for col in range(width):
                if (byte >> col) & 1:
                    mask[r, x + col] = True
        x += width
    return mask


def find(frame_png: str | Path | Image.Image | np.ndarray, text: str,
         proportional: bool | None = None) -> list[tuple[int, int, tuple[int, int, int]]]:
    """Search `frame_png` (a path or an already-loaded PIL Image / ndarray) for an
    EXACT pixel match of render(text, proportional). proportional=None tries
    BOTH renderers (ui_ptext's and ui_text's fonts) since the caller does not
    know a priori which one drew a given piece of UI text.

    Returns a list of (x, y, colour) hits -- (x, y) is the top-left corner of
    the match, colour is the (R, G, B) the glyph was drawn in on that frame.
    Empty list = not found."""
    if isinstance(frame_png, np.ndarray):
        arr = frame_png
    else:
        img = frame_png if isinstance(frame_png, Image.Image) else Image.open(frame_png)
        arr = np.asarray(img.convert("RGB"))

    modes = [True, False] if proportional is None else [proportional]
    hits: list[tuple[int, int, tuple[int, int, int]]] = []
    for prop in modes:
        mask = render(text, proportional=prop)
        h, w = mask.shape
        if h == 0 or w == 0 or h > arr.shape[0] or w > arr.shape[1]:
            continue
        colours, counts = np.unique(arr.reshape(-1, arr.shape[-1]), axis=0, return_counts=True)
        if len(colours) > MAX_COLOURS_SCANNED:
            # Bounded fallback for a >256-colour frame (a sprite/gameplay screen,
            # not a UI render) -- see the module docstring's FIND section and
            # MAX_COLOURS_SCANNED above. Never raise: search only the most
            # frequent colours and let a miss fall out as a normal empty result.
            order = np.argsort(-counts)[:MAX_COLOURS_SCANNED]
            colours = colours[order]
        for colour in colours:
            plane = np.all(arr == colour, axis=-1)
            windows = sliding_window_view(plane, (h, w))
            matches = np.all(windows == mask, axis=(2, 3))
            ys, xs = np.nonzero(matches)
            for y, x in zip(ys.tolist(), xs.tolist()):
                hits.append((x, y, tuple(int(c) for c in colour)))
    return hits


def check(frame_png: str | Path | Image.Image | np.ndarray,
          claim: str | list[str] | None = None, claim_absent: str | list[str] | None = None,
          proportional: bool | None = None) -> list[str]:
    """The shared gate used by both Session.shot() (live, BACKLOG #184 item 2) and
    --selftest-captions's offline re-check (item 2's extension): returns a list
    of human-readable failure strings (empty = every claim/claim_absent held).
    `claim`/`claim_absent` are each a string or a list of strings (None = no
    check of that kind)."""
    def as_list(v):
        if v is None:
            return []
        return [v] if isinstance(v, str) else list(v)

    failures: list[str] = []
    for text in as_list(claim):
        if not find(frame_png, text, proportional=proportional):
            failures.append(f"'{text}' not on frame")
    for text in as_list(claim_absent):
        if find(frame_png, text, proportional=proportional):
            failures.append(f"'{text}' unexpectedly ON frame (claim_absent)")
    return failures


# =============================================================================
# claim_gb= -- the GB-shell (gbscr_text) matcher, BACKLOG #214 item 2.
#
# WHY find()/render() DO NOT COVER THIS
# --------------------------------------
# The Hall of Fame card, the Gen-1/2 trainer card and the other
# pdna_gbscreen.c "shell" screens draw their text through gbscr_text()
# (source/pdna_gbscreen.c), which paints ONE FONT TILE PER COLUMN read
# straight out of the user's own registered Game Boy ROM (rom_gbui_glyph(),
# source/rom_gbui.c) -- a THIRD font source, neither source/ui_font.c's
# ui_font_bits (render(proportional=True)) nor tonc's sys8Font
# (render(proportional=False)). Its pixel shapes are Game-Freak-owned and
# differ per game/release, so they can never be a literal in this repo
# (BACKLOG #184's original v1 scoped this out for exactly that reason -- see
# tools/dgb_shots.py's b184-revert comments on run_b89_hof/run_b194_hof).
# BACKLOG #118's own finding also rules out reading a live GB PPU/tilemap the
# way tools/gb_oracle/oracle.py's compose() does: the shot harness's Session
# wraps a GBA core in DCNT_MODE3 (a bitmap framebuffer), and gbscr's shell
# composites onto that bitmap directly -- there is no tilemap to read from
# "VRAM" here at all.
#
# THE FIX: read the SAME ROM FILE the shot was booted from
# ----------------------------------------------------------
# Nothing is embedded. tools/gbclaim_font_driver.c compiles the SHIPPED
# source/rom_gbui.c (the font locator) and source/gb_edit.c
# (gb_char_encode(), the exact ASCII->GB-charcode table gbscr_text() itself
# calls) against a tiny main() and, for each requested claim string, walks
# the identical "gb_char_encode() -> rom_gbui_glyph()" loop
# gbscr_text()/gbscr_tile_pixels() run on real hardware -- against the
# caller's own ROM file, read fresh every call, never cached to disk (same
# clean-room posture tools/gbui_dump.py's own header documents: "this script
# does not locate anything itself -- it only invokes the already-reviewed C
# locator"). The result is an exact 1bpp ink/background bitmap per glyph
# (rom_gbui_tile()'s own 1bpp rule: the raw bit IS the ink/background
# decision, "hi = lo" so idx is 0 or 3 -- no grey levels in the font).
#
# THE GRID: gbscr's own known 8x8 layout, not a sliding search
# ----------------------------------------------------------------
# gbscr_text() places one glyph per COLUMN on a fixed GBSCR_COLS(20) x
# GBSCR_ROWS(18) canvas; in the default (gb_scale_mode == 0, "1:1") layout
# blit_1to1() (source/pdna_gbscreen.c) places cell (cx, cy)'s 8x8 block at
# pixel (GBSCR_ORIGIN_X + cx*8, GBSCR_ORIGIN_Y + cy*8) = (40 + cx*8, 8 + cy*8)
# -- both constants read straight from source/pdna_gbscreen.h, not guessed.
# find_gb() therefore does not slide pixel-by-pixel like find(): it only
# tries the GBSCR_COLS*GBSCR_ROWS discrete cell-aligned starting positions a
# real glyph run could ever begin at, and requires an EXACT match (every ink
# bit AND every background bit of the claim's rendered glyphs) against the
# frame's own pixels there -- the same "gap pixels must not be ink either"
# contract render()/find() already document, here expressed as "every
# non-claimed pixel in the glyph's own 8x8 cell must be background". A blank
# glyph (ASCII space, gb_char_encode() -> 0x7F) matches gbscr's
# GBSCR_BLANK_COLOR cell (solid background, source/pdna_gbscreen.c) exactly
# the same way. This is a best-effort, scale-mode-0-only matcher: every
# claim_gb= shot this lane adds runs with the shell's default (unstretched)
# scale, the only mode any runner in this tree reaches without an explicit
# SELECT tap (gb_scale_mode's own default is 0, source/pdna_gbscreen.c).
# =============================================================================

GBUI_DRIVER_SRC = ROOT / "tools" / "gbclaim_font_driver.c"
GBUI_C_SOURCES = [
    "rom_gbui.c", "gb_edit.c", "data_tables.c", "gen1_save.c", "gen2_save.c",
    "gen1_write.c", "gen2_write.c", "gb_session.c",
    "item_map_g2g3.c", "item_map_g1g2.c", "gb_item_names.c", "gb_bag.c", "gb_fields.c",
    "gen3_to_gb.c", "gb_sidecar.c", "bank_cell.c", "gen3_edit.c", "gen3_mon.c",
    "gen3_box.c", "gen3_save.c", "gen3_daycare.c",
]  # BACKLOG #214: the exact link list tests/host_gbhof_glyph_test.c's own header
   # documents for gb_edit.c's transitive Gen-1/2 dependencies, plus rom_gbui.c
   # for the font locator -- never hand-picked, copied from that test's recipe.
   # BACKLOG #248/#249 (xfer-items): gen3_to_gb.c now calls item_g3_to_g2()/
   # item_g2_to_g1(), and item_g2_to_g1() calls gbb_is_g1_key_item() -- the same
   # four extra modules (+ their gen1_write/gen2_write/gb_session transitive deps)
   # host_gbhof_glyph_test.c's own header picked up when this lane added them there.

# GB-shell 1:1 layout constants -- source/pdna_gbscreen.h's own #defines, read
# once here rather than re-typed at every call site.
GBSCR_ORIGIN_X = 40
GBSCR_ORIGIN_Y = 8
GBSCR_COLS = 20
GBSCR_ROWS = 18
GB_CELL = 8

# BACKLOG #254: find_gb() missed a claim on a SELECTED row (b89_crystal_02_detail.png,
# claim_gb=TYPHLOSION) because the GB shell's row/field cursor is drawn AFTER the
# text, on top of it -- source/pdna_gbhof.c's hof_card_screen() and
# source/pdna_gbtrainer.c's g1card_screen()/g2card_screen() all call
# gbscr_cell_rect()+m3_frame(px0, py0, px1, py1, GBCARD_CSEL) every frame the cursor
# is shown, and m3_frame() is a 1px RECTANGLE OUTLINE (top+bottom+left+right lines),
# not a fill -- it repaints exactly the cursor cell's own border pixels in ONE fixed
# colour, GBCARD_CSEL, #define'd identically in both files as RGB15(26, 4, 3).
# A raw pixel dump of the b89 repro (this lane, BACKLOG #254) proved the corruption
# is narrow and exact: at the correct glyph-cell alignment (x=64, the row's real text
# start per HOF_CARD_TEXT_X, not the icon's own column), rows 1..6 of the 8-row glyph
# window are a PIXEL-EXACT match against render_gb()'s own mask, and only row 0 (the
# cursor's top border line) and row 7 (its bottom border line) are wrong -- both
# entirely this one hardcoded colour, never a blend and never a sprite hue (the icon
# stays inside its own 16px cell and never reaches the text columns on this repro).
# Because gbscr_text()'s own rendering is strictly two colours (the row's ink colour
# or GBSCR_BLANK_COLOR background -- see render_gb()'s 1bpp contract), a pixel that
# is EXACTLY this named constant can never be genuine glyph ink OR genuine glyph
# background; find_gb() below excludes ONLY this one exact RGB triple from both the
# ink-uniformity check and the background-must-differ check -- not "any third
# colour", so a genuinely wrong letter (which still renders in the row's normal two
# colours) is still a hard mismatch, and a sprite-icon hue landing on a glyph cell
# (not reproduced here, but not ruled out on a denser row) still is too.
# A window where too much of its own ink is this cursor colour has nothing left to
# disambiguate the real letters from a different string of the same length -- past
# GB_CURSOR_OCCLUSION_CAP, find_gb() refuses to call the window a hit (would risk a
# false positive) OR silently drop it as a plain miss (would repeat BACKLOG #254's
# false negative); it reports the position via the `occluded` out-param instead, and
# check_gb() surfaces that as its own distinct, honest failure string.
GBCARD_CSEL_RGB15 = (26, 4, 3)   # source/pdna_gbhof.c:54, source/pdna_gbtrainer.c:48


def _rgb15_to_rgb888(r5: int, g5: int, b5: int) -> tuple[int, int, int]:
    """The GBA's own 5-bit -> 8-bit channel expansion (v<<3 | v>>2) -- the same
    formula every core (and this repo's own shot harness) uses turning a Mode-3
    RGB555 pixel into the RGB888 a captured PNG stores. Verified against the b89
    repro's own measured border pixel: RGB15(26,4,3) -> (214, 33, 24), exactly
    what this function returns and exactly what docs/shots/gb/b89_crystal_02_detail
    .png's border pixels measure."""
    def conv(v: int) -> int:
        return (v << 3) | (v >> 2)
    return (conv(r5), conv(g5), conv(b5))


GBCARD_CSEL_RGB = _rgb15_to_rgb888(*GBCARD_CSEL_RGB15)   # (214, 33, 24)
GB_CURSOR_OCCLUSION_CAP = 0.5   # refuse rather than guess above this ink-pixel fraction

_gb_driver_bin: Path | None = None
_gb_driver_build_failed: str | None = None


def _gb_driver() -> Path | None:
    """Compile tools/gbclaim_font_driver.c once per process (cc, no devkitARM
    needed -- same host-`cc` posture tools/gbui_dump.py's build_driver() and
    every tests/host_*_test.c recipe already use). Returns None (cached) if
    this host has no C compiler -- callers surface that as a clear failure,
    never a silent claim pass."""
    global _gb_driver_bin, _gb_driver_build_failed
    if _gb_driver_bin is not None or _gb_driver_build_failed is not None:
        return _gb_driver_bin
    cc = shutil.which("cc") or shutil.which("gcc") or shutil.which("clang")
    if not cc:
        _gb_driver_build_failed = "no host C compiler (cc/gcc/clang) found"
        return None
    src_dir = ROOT / "source"
    bin_dir = Path(tempfile.mkdtemp(prefix="gbclaim_"))
    binp = bin_dir / "gbclaim_font_driver"
    cmd = [cc, "-std=c11", "-O1", "-I", str(src_dir), str(GBUI_DRIVER_SRC)]
    cmd += [str(src_dir / name) for name in GBUI_C_SOURCES]
    cmd += ["-o", str(binp)]
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode != 0 or not binp.is_file():
        _gb_driver_build_failed = f"build failed: {r.stderr.strip()[-2000:]}"
        return None
    _gb_driver_bin = binp
    return _gb_driver_bin


def _gb_glyph_tokens(rom_path: str | Path, texts: list[str]) -> dict[str, list[str] | None]:
    """Run the compiled driver once for this ROM against every text in `texts`
    (batched -- one process launch, not one per claim). Returns text -> list
    of glyph tokens ("BLANK" or 16 lowercase hex digits), or None if that
    text could not be encoded/rendered on this ROM's font (a claim on it then
    reports a clear reason, not a silent miss)."""
    binp = _gb_driver()
    if binp is None:
        raise RuntimeError(f"claim_gb=: cannot build the GB font driver ({_gb_driver_build_failed})")
    rom_path = Path(rom_path)
    if not rom_path.is_file():
        raise RuntimeError(f"claim_gb=: ROM not found: {rom_path}")
    r = subprocess.run([str(binp), str(rom_path), *texts], capture_output=True, text=True)
    lines = r.stdout.splitlines()
    out: dict[str, list[str] | None] = {}
    for text, line in zip(texts, lines):
        if "\t" not in line:
            out[text] = None
            continue
        tag, body = line.split("\t", 1)
        out[text] = body.split(",") if tag == "OK" else None
    for text in texts:
        out.setdefault(text, None)
    return out


def render_gb(rom_path: str | Path, text: str) -> np.ndarray | None:
    """Render `text` the way gbscr_text() draws it on `rom_path`'s own font,
    as an (8, 8*len(glyphs)) bool array (True = ink), one 8px-wide cell per
    glyph -- see this section's module-level design comment. None if the ROM
    or this text's glyphs could not be resolved (never raises for a normal
    "this ROM's font doesn't have that" case, matching find()'s no-raise
    contract; a missing ROM/compiler still raises -- that is a setup error,
    not a claim result)."""
    tokens = _gb_glyph_tokens(rom_path, [text])[text]
    if tokens is None:
        return None
    n = len(tokens)
    mask = np.zeros((GB_CELL, GB_CELL * n), dtype=bool)
    for i, tok in enumerate(tokens):
        if tok == "BLANK":
            continue
        rows = bytes.fromhex(tok)
        for r, byte in enumerate(rows):
            for c in range(GB_CELL):
                if (byte >> (7 - c)) & 1:      # bit 7 = leftmost pixel (driver's own doc comment)
                    mask[r, i * GB_CELL + c] = True
    return mask


def find_gb(frame_png: str | Path | Image.Image | np.ndarray, rom_path: str | Path,
            text: str, occluded: list[tuple[int, int, float]] | None = None
            ) -> list[tuple[int, int]]:
    """Search `frame_png` for an EXACT match of `text` rendered through
    `rom_path`'s own GB font (render_gb()), at every gbscr 1:1-layout cell
    position (GBSCR_ORIGIN_X/Y + col/row*8) -- see this section's design
    comment for why this is a fixed-grid search, not find()'s sliding one.
    Returns a list of (x, y) top-left hits; empty = not found (including "this
    ROM's font can't render this text at all", the same not-found semantics
    find() already gives >256-colour frames -- see MAX_COLOURS_SCANNED).

    BACKLOG #254: a pixel that is EXACTLY GBCARD_CSEL_RGB (the GB shell's
    row/field cursor colour, drawn AFTER the text by m3_frame() -- see this
    section's module-level design comment right above GBCARD_CSEL_RGB15) is
    excluded from both the ink-uniformity check and the background-must-differ
    check at that one position, not treated as a match OR a mismatch either
    way. If `occluded` is passed, every candidate window this exclusion was
    needed to accept, but whose ink pixels were MORE than
    GB_CURSOR_OCCLUSION_CAP cursor-coloured (too little real ink left to trust
    the match), is appended to it as (x, y, occluded_fraction) and NOT
    returned as a hit -- callers that want the honest "cannot decide" signal
    (check_gb()) pass a list here; callers happy with plain hit/no-hit don't."""
    mask = render_gb(rom_path, text)
    if mask is None:
        return []
    h, w = mask.shape
    n_glyphs = w // GB_CELL
    if n_glyphs == 0 or n_glyphs > GBSCR_COLS:
        return []

    if isinstance(frame_png, np.ndarray):
        arr = frame_png
    else:
        img = frame_png if isinstance(frame_png, Image.Image) else Image.open(frame_png)
        arr = np.asarray(img.convert("RGB"))

    cursor_rgb = np.array(GBCARD_CSEL_RGB)
    hits: list[tuple[int, int]] = []
    for row in range(GBSCR_ROWS):
        y = GBSCR_ORIGIN_Y + row * GB_CELL
        if y + h > arr.shape[0]:
            continue
        for col in range(GBSCR_COLS - n_glyphs + 1):
            x = GBSCR_ORIGIN_X + col * GB_CELL
            if x + w > arr.shape[1]:
                continue
            crop = arr[y:y + h, x:x + w]
            # Exact match: every ink pixel of the mask must be a SINGLE colour
            # (the glyph's own ink colour, not known a priori -- same
            # reasoning find()'s own docstring gives) and every non-ink pixel
            # must NOT be that colour (the gap/background requirement) --
            # EXCEPT pixels the GB shell's own cursor overlay could have
            # painted (BACKLOG #254), which are set aside from both checks.
            ink_px = crop[mask]
            if ink_px.size == 0:
                continue   # an all-blank claim (pure whitespace) can't anchor a colour
            cursor_at_ink = np.all(ink_px == cursor_rgb, axis=-1)
            occl_frac = float(cursor_at_ink.mean())
            real_ink = ink_px[~cursor_at_ink]
            if real_ink.size == 0:
                # every ink pixel the mask needs is cursor-coloured -- nothing
                # left to anchor a colour on at all, the strongest "cannot
                # decide" case.
                if occluded is not None:
                    occluded.append((x, y, 1.0))
                continue
            colour = real_ink[0]
            if not np.all(real_ink == colour):
                continue
            bg_px = crop[~mask]
            if bg_px.size:
                cursor_at_bg = np.all(bg_px == cursor_rgb, axis=-1)
                real_bg = bg_px[~cursor_at_bg]
                if real_bg.size and np.any(np.all(real_bg == colour, axis=-1)):
                    continue
            if occl_frac > GB_CURSOR_OCCLUSION_CAP:
                if occluded is not None:
                    occluded.append((x, y, occl_frac))
                continue
            hits.append((x, y))
    return hits


def check_gb(frame_png: str | Path | Image.Image | np.ndarray, rom_path: str | Path,
             claim_gb: str | list[str] | None = None) -> list[str]:
    """claim_gb='s own check(), same failure-string contract as check(). Every
    string in `claim_gb` must be found via find_gb() against `rom_path`'s own
    GB font; a miss is a normal (non-raising) failure string.

    BACKLOG #254: a claim whose only near-matches were too occluded by the GB
    shell's cursor colour to trust (find_gb()'s `occluded` out-param) gets its
    OWN failure string -- distinct wording from a genuine "not on frame" miss,
    so a caller (or a human) can tell "the text is not there" apart from "the
    matcher refuses to guess here" instead of the two collapsing into the same
    confident-sounding false negative BACKLOG #254 found."""
    if claim_gb is None:
        return []
    texts = [claim_gb] if isinstance(claim_gb, str) else list(claim_gb)
    failures: list[str] = []
    for text in texts:
        occluded: list[tuple[int, int, float]] = []
        if find_gb(frame_png, rom_path, text, occluded=occluded):
            continue
        if occluded:
            frac = max(o[2] for o in occluded)
            failures.append(
                f"'{text}' cannot be verified on frame (claim_gb): the GB-shell "
                f"cursor highlight covers {frac:.0%} of its own ink pixels at the "
                f"best candidate position -- refusing rather than guessing "
                f"(BACKLOG #254)")
        else:
            failures.append(f"'{text}' not on frame (claim_gb)")
    return failures
