#!/usr/bin/env python3
"""Build the companion sprite pack for the TRIMMED SD build.

The shiny-front + back sprite blobs are dropped from the ROM (to fit the EZ-Flash SD-mode
PSRAM budget) and concatenated here into data/sprites.pak, which ships alongside the ROM and
is copied to /PokeDNA/sprites.pak on the card. source/sprite_pak.h gives each blob's base
byte offset in the pack; the mon_front/mon_back accessors add the per-sprite offset and stream
that one LZ77 sprite via sprite_stream(). The per-sprite offset tables (off_s / off_n / uform /
dform) are UNCHANGED — they're relative to each blob's start, and each blob keeps its byte
layout here (only zero-padded to a 4-byte boundary at the END, which the LZ77 header-terminated
decompressor ignores). Run AFTER gen_front.py + gen_back.py (it reads their .bin outputs).
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FS = os.path.join(ROOT, "data", "mon_front_shiny.bin")   # front shiny  -> PAK_FS_BASE
BN = os.path.join(ROOT, "data", "mon_back.bin")          # back normal  -> PAK_BN_BASE
BS = os.path.join(ROOT, "data", "mon_back_shiny.bin")    # back shiny   -> PAK_BS_BASE
OUT_PAK = os.path.join(ROOT, "data", "sprites.pak")
OUT_H = os.path.join(ROOT, "source", "sprite_pak.h")


def pad4(b):
    return b + b"\x00" * ((4 - len(b) % 4) % 4)


def main():
    fs = pad4(open(FS, "rb").read())
    bn = pad4(open(BN, "rb").read())
    bs = pad4(open(BS, "rb").read())
    fs_base, bn_base, bs_base = 0, len(fs), len(fs) + len(bn)
    with open(OUT_PAK, "wb") as f:
        f.write(fs); f.write(bn); f.write(bs)
    with open(OUT_H, "w") as h:
        h.write("/* GENERATED by tools/gen_pak.py - do not edit. */\n")
        h.write("#ifndef SPRITE_PAK_H\n#define SPRITE_PAK_H\n")
        h.write("/* Base byte offsets of each blob within /PokeDNA/sprites.pak (trimmed SD build). */\n")
        h.write("#define PAK_FS_BASE 0x%08xu   /* front shiny */\n" % fs_base)
        h.write("#define PAK_BN_BASE 0x%08xu   /* back normal */\n" % bn_base)
        h.write("#define PAK_BS_BASE 0x%08xu   /* back shiny  */\n" % bs_base)
        h.write("#endif\n")
    total = len(fs) + len(bn) + len(bs)
    print("sprites.pak: front_shiny %.2f + back %.2f + back_shiny %.2f = %.2f MiB -> copy to /PokeDNA/sprites.pak"
          % (len(fs) / 1048576.0, len(bn) / 1048576.0, len(bs) / 1048576.0, total / 1048576.0))


if __name__ == "__main__":
    main()
