#!/usr/bin/env python3
"""Convert the 18 real Gen-3 type-label badges (pret/pokeemerald graphics/types/)
into a git-ignored RGB15 blob, indexed by the Gen-3 internal type id 0..17.

Same posture as gen_icons.py / gen_hand.py: Nintendo art is never committed — the
PNGs live under assets/types/ (git-ignored) and the generated source/type_icons.{c,h}
are git-ignored too. Each PNG carries its OWN 16-colour palette (there are 3 distinct
palettes across the 18), so we read getpalette() per file. Index 0 is transparent.

Pixel convention (matches icons / front sprites / hand):
  u16 = 0x0000           transparent (palette index 0)
      = 0x8000 | rgb15   opaque
"""
import os
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRCDIR = os.path.join(ROOT, "assets", "types")
OUTC = os.path.join(ROOT, "source", "type_icons.c")
OUTH = os.path.join(ROOT, "source", "type_icons.h")

# Gen-3 internal type id -> source filename (id 9 = the unused ??? / MYSTERY type).
TYPES = [
    "normal", "fight", "flying", "poison", "ground", "rock", "bug", "ghost",
    "steel", "mystery", "fire", "water", "grass", "electric", "psychic", "ice",
    "dragon", "dark",
]


def rgb15(r, g, b):
    return (r >> 3) | ((g >> 3) << 5) | ((b >> 3) << 10)


def load_indexed(name):
    im = Image.open(os.path.join(SRCDIR, name + ".png"))
    if im.mode != "P":
        im = im.convert("P")
    return im, im.getpalette(), im.load()


def main():
    imgs = [load_indexed(t) for t in TYPES]
    W, H = imgs[0][0].size                      # 32x16, all identical

    # shared tight bounding box of every non-transparent pixel across all 18
    xs, ys = [], []
    for im, _, px in imgs:
        for y in range(H):
            for x in range(W):
                if px[x, y] != 0:
                    xs.append(x); ys.append(y)
    x0, x1 = min(xs), max(xs)
    y0, y1 = min(ys), max(ys)
    cw, ch = x1 - x0 + 1, y1 - y0 + 1

    blob = []
    for im, pal, px in imgs:
        for y in range(y0, y1 + 1):
            for x in range(x0, x1 + 1):
                idx = px[x, y]
                if idx == 0:
                    blob.append(0)
                else:
                    r, g, b = pal[idx * 3], pal[idx * 3 + 1], pal[idx * 3 + 2]
                    blob.append(0x8000 | rgb15(r, g, b))

    with open(OUTH, "w") as f:
        f.write("/* GENERATED by tools/gen_types.py - do not edit, do not commit. */\n")
        f.write("#ifndef TYPE_ICONS_INCLUDED\n#define TYPE_ICONS_INCLUDED\n")
        f.write("#include <stdint.h>\n")
        f.write(f"#define TYPE_ICON_W {cw}\n#define TYPE_ICON_H {ch}\n")
        f.write("#define TYPE_ICON_N 18\n")
        f.write("extern const uint16_t type_icons[TYPE_ICON_N * TYPE_ICON_W * TYPE_ICON_H];\n")
        f.write("/* &type_icons[t * W*H]; t = Gen-3 internal type id 0..17 (9 = unused). */\n")
        f.write("const uint16_t* type_icon_for(uint8_t t);\n")
        f.write("#endif\n")

    with open(OUTC, "w") as f:
        f.write("/* GENERATED by tools/gen_types.py - do not edit, do not commit. */\n")
        f.write('#include "type_icons.h"\n\n')
        f.write("const uint16_t type_icons[TYPE_ICON_N * TYPE_ICON_W * TYPE_ICON_H] = {\n")
        per = cw * ch
        for t, name in enumerate(TYPES):
            f.write(f"  /* {t}: {name} */\n  ")
            row = blob[t * per:(t + 1) * per]
            f.write(",".join("0x%04X" % v for v in row) + ",\n")
        f.write("};\n\n")
        f.write("const uint16_t* type_icon_for(uint8_t t) {\n")
        f.write("  if (t >= TYPE_ICON_N) t = 0;\n")
        f.write("  return &type_icons[(uint32_t)t * TYPE_ICON_W * TYPE_ICON_H];\n}\n")

    print(f"type_icons: bbox ({x0},{y0})-({x1},{y1}) -> {cw}x{ch} per icon, {len(TYPES)} icons")


if __name__ == "__main__":
    main()
