#!/usr/bin/env python3
"""Build a 4bpp-OAM version of the PC-storage hand cursor + grab fist from the
existing RGB15 hand_cursor.c, for the hardware-sprite box screen.

The box grid is composited from OBJ sprites; the cursor hand and the move-mode
grab fist sit ON TOP of those icon sprites, so they must be sprites too (a software
blit on the BG bitmap would be hidden behind the icon sprites). Each is packed into
a 32x32 (16-tile) 4bpp sprite sharing ONE 16-colour palette (the hand art uses only
a handful of colours -> lossless).

INPUT  (git-ignored, produced by tools/gen_hand.py):
  source/hand_cursor.c / .h     hand_cursor[18x20], hand_grab[18x17] RGB15 arrays
OUTPUT (git-ignored, derived art):
  source/hand_oam.{c,h}         tiles + shared palette, C arrays (small -> no incbin)

Run from the repo root:  python3 tools/gen_hand_oam.py   (stdlib only)
"""
import os, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
IN_C = os.path.join(ROOT, "source", "hand_cursor.c")
IN_H = os.path.join(ROOT, "source", "hand_cursor.h")
OUT_C = os.path.join(ROOT, "source", "hand_oam.c")
OUT_H = os.path.join(ROOT, "source", "hand_oam.h")

CELL = 32                 # pack each frame into a 32x32 sprite (top-left aligned)
PAL_ENTRIES = 16


def parse_dims(h):
    txt = open(h).read()
    d = {}
    for m in re.finditer(r"#define\s+(HAND\w*?_([WH]))\s+(\d+)", txt):
        d[m.group(1)] = int(m.group(3))
    return d


def parse_array(c, name):
    txt = open(c).read()
    m = re.search(re.escape(name) + r"\[[^\]]*\]\s*=\s*\{(.*?)\};", txt, re.S)
    if not m:
        raise SystemExit("array %s not found in %s" % (name, c))
    return [int(x, 16) for x in re.findall(r"0x[0-9A-Fa-f]+", m.group(1))]


def main():
    dims = parse_dims(IN_H)
    frames = [
        ("hand_cursor", dims["HAND_W"], dims["HAND_H"]),
        ("hand_grab",   dims["HAND_GRAB_W"], dims["HAND_GRAB_H"]),
    ]

    # one shared palette across both frames (slot 0 transparent)
    pal = [0]
    palmap = {}

    def idx(v):
        c = v & 0x7FFF
        if c in palmap:
            return palmap[c]
        if len(pal) >= PAL_ENTRIES:
            raise SystemExit("hand art needs >15 colours; widen palette logic")
        palmap[c] = len(pal)
        pal.append(c)
        return palmap[c]

    framedata = []
    for name, w, h in frames:
        arr = parse_array(IN_C, name)
        # 32x32 index grid, top-left aligned, rest transparent (0)
        grid = [0] * (CELL * CELL)
        for y in range(h):
            for x in range(w):
                p = arr[y * w + x]
                if p & 0x8000:
                    grid[y * CELL + x] = idx(p)
        # pack 16 tonc 8x8 4bpp tiles (4x4, row-major, 1D mapping)
        tiles = bytearray()
        for ty in range(CELL // 8):
            for tx in range(CELL // 8):
                for ry in range(8):
                    py = ty * 8 + ry
                    for rx in range(0, 8, 2):
                        px = tx * 8 + rx
                        lo = grid[py * CELL + px]
                        hi = grid[py * CELL + px + 1]
                        tiles.append((lo & 0xF) | ((hi & 0xF) << 4))
        framedata.append((name, bytes(tiles)))

    while len(pal) < PAL_ENTRIES:
        pal.append(0)

    ntiles = (CELL // 8) * (CELL // 8)
    with open(OUT_H, "w") as h:
        h.write("/* GENERATED by tools/gen_hand_oam.py - do not edit. */\n")
        h.write("#ifndef HAND_OAM_INCLUDED\n#define HAND_OAM_INCLUDED\n#include <stdint.h>\n\n")
        h.write("#define HAND_OAM_TILES %d   /* 32x32 sprite = 16 4bpp tiles */\n" % ntiles)
        h.write("#define HAND_OAM_TILE_BYTES 32\n\n")
        h.write("extern const uint8_t  hand_oam_cursor_tiles[HAND_OAM_TILES * HAND_OAM_TILE_BYTES];\n")
        h.write("extern const uint8_t  hand_oam_grab_tiles[HAND_OAM_TILES * HAND_OAM_TILE_BYTES];\n")
        h.write("extern const uint16_t hand_oam_pal[16];  /* slot 0 transparent */\n\n#endif\n")

    with open(OUT_C, "w") as c:
        c.write("/* GENERATED by tools/gen_hand_oam.py - do not edit. */\n")
        c.write('#include "hand_oam.h"\n\n')
        for name, tiles in framedata:
            cname = "hand_oam_%s_tiles" % ("cursor" if name == "hand_cursor" else "grab")
            c.write("const uint8_t %s[HAND_OAM_TILES * HAND_OAM_TILE_BYTES] = {\n" % cname)
            for i in range(0, len(tiles), 16):
                c.write("  " + ",".join("0x%02x" % b for b in tiles[i:i + 16]) + ",\n")
            c.write("};\n\n")
        c.write("const uint16_t hand_oam_pal[16] = {%s};\n" %
                ",".join("0x%04x" % v for v in pal))

    print("hand oam: 2 frames x %d tiles, %d palette colours used" % (ntiles, len(palmap) + 1))


if __name__ == "__main__":
    main()
