#!/usr/bin/env python3
"""Generate source/daycare_bg_data.h from a user-supplied daycare MAP image.

Treats the picture as the daycare scene background: fits it to the 240x112 scene
region (screen rows 12..124) as RGB15, the format the box/daycare blitter expects.
Also writes a 3x preview with the per-area mon SLOTS overlaid so placement can be
eyeballed against the terrain. Output .h is git-ignored (generate locally).

Usage:  python3 tools/gen_daycare_img.py "<path-to-map.png>"
"""
import sys, os
from PIL import Image, ImageDraw

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT  = os.path.join(ROOT, "source", "daycare_bg_data.h")
W, H = 240, 112          # daycare scene region (matches the blitter / DC_SPOT coords)
SCENE_Y = 12             # bg is blitted at screen y=12

# Per-area mon SLOTS, in SCREEN coords (icon CENTRE). 2 slots per area so two mons in
# the same area don't overlap. Keep cy>=28 (icon top>=12) and cy<=108 (bottom<124).
# These must mirror DC_SPOT[][] in pdna_main.c.
SLOTS = {
  "LAVA":  [(32, 34), (54, 42)],     # red area, top-left
  "ELEC":  [(94, 38), (120, 46)],    # yellow diamond area, centre-top
  "SKY":   [(160, 30), (205, 34)],   # trees, top-right
  "WATER": [(158, 86), (210, 92)],   # water below the waterfall, right
  "GRASS": [(28, 98), (64, 106)],    # grass + flowers, bottom-left
  "EMPTY": [(100, 90), (128, 104)],  # plain grass, centre-bottom
}
COL = {"LAVA":(255,80,80),"ELEC":(255,230,60),"SKY":(120,220,120),
       "WATER":(80,160,255),"GRASS":(120,255,120),"EMPTY":(230,230,230)}

def to_rgb15(r, g, b):
    return (r >> 3) | ((g >> 3) << 5) | ((b >> 3) << 10)

def main():
    if len(sys.argv) < 2:
        print("usage: gen_daycare_img.py <map.png>"); return 1
    src = Image.open(sys.argv[1]).convert("RGB").resize((W, H), Image.LANCZOS)

    # --- emit the .h ---
    px = src.load()
    with open(OUT, "w") as f:
        f.write("/* GENERATED by tools/gen_daycare_img.py - do not edit. GIT-IGNORED. */\n")
        f.write("#ifndef DAYCARE_BG_DATA_H\n#define DAYCARE_BG_DATA_H\n")
        f.write("#define DAYCARE_BG_W %d\n#define DAYCARE_BG_H %d\n" % (W, H))
        f.write("static const unsigned short __attribute__((aligned(4)))\n")
        f.write("  daycare_bg[DAYCARE_BG_W*DAYCARE_BG_H] = {\n")
        out = []
        for y in range(H):
            for x in range(W):
                r, g, b = px[x, y]
                out.append("0x%04x" % to_rgb15(r, g, b))
        for i in range(0, len(out), 16):
            f.write("  " + ",".join(out[i:i+16]) + ",\n")
        f.write("};\n#endif\n")
    print("wrote", OUT, "(%dx%d)" % (W, H))

    # --- overlay preview (3x) with the slot footprints (32x32, drawn at cy-16) ---
    ov = src.copy().resize((W*3, H*3), Image.NEAREST)
    d = ImageDraw.Draw(ov)
    for area, slots in SLOTS.items():
        for (cx, cy) in slots:
            bx, by = cx, cy - SCENE_Y      # bg-relative
            x0, y0 = (bx-16)*3, (by-16)*3
            d.rectangle([x0, y0, x0+32*3, y0+32*3], outline=COL[area], width=2)
            d.text((x0+2, y0+2), area[0], fill=COL[area])
    ov.save("/tmp/daycare_overlay.png")
    print("wrote /tmp/daycare_overlay.png")
    return 0

if __name__ == "__main__":
    sys.exit(main())
