#!/usr/bin/env python3
"""Convert the Gen-3 sprite-pack box icons into a committed C blob.

For each species PNG (Graphics/Pokemon/Icons/<NAME>.png, a 128x64 sheet = two
64x64 frames), take frame 0, downscale to 16x16, and store each pixel as a u16:
  0x0000          -> transparent
  0x8000 | RGB15  -> opaque
Emit source/mon_icons.{c,h} with:
  mon_icon_data[N][256]      the 16x16 icons
  mon_icon_index[412]        internal Gen-3 species id -> row in mon_icon_data
                             (0xFFFF if none)
Run from the repo root:  python3 tools/gen_icons.py   (needs Pillow)
The generated source/mon_icons.{c,h} and the sprite pack are git-ignored (ripped
art, not redistributed), so regenerate locally before building with icons.
"""
import os, re, sys
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# Sprite pack lives under assets/sprites/ (git-ignored; not redistributed).
PACK = os.path.join(ROOT, "assets", "sprites", "Gen 3 Sprite Pack V1")
ICONS = os.path.join(PACK, "Graphics", "Pokemon", "Icons")
PBS = os.path.join(PACK, "PBS", "pokemon_metrics.txt")
OUT_C = os.path.join(ROOT, "source", "mon_icons.c")
OUT_H = os.path.join(ROOT, "source", "mon_icons.h")

MAX_INTERNAL = 411   # Gen 3 internal species ceiling


def norm(s):
    return re.sub(r"[^A-Z0-9]", "", s.upper())


def species_map():
    """norm(species name) -> INTERNAL Gen-3 id, straight from the decomp constants
    (SPECIES_KYOGRE=404 etc.) — the exact id the save stores. The old national+25
    shortcut mismapped the displaced legendaries (Kyogre showed Registeel)."""
    path = os.path.join(ROOT, "reference", "pokeemerald_data", "include", "constants", "species.h")
    m = {}
    with open(path) as f:
        for line in f:
            mm = re.match(r"\s*#define\s+SPECIES_(\w+)\s+(\d+)", line)
            if mm:
                m[norm(mm.group(1))] = int(mm.group(2))
    if "NIDORANF" in m: m["NIDORANFE"] = m["NIDORANF"]
    if "NIDORANM" in m: m["NIDORANMA"] = m["NIDORANM"]
    return m


def rgb15(r, g, b):
    return (r >> 3) | ((g >> 3) << 5) | ((b >> 3) << 10)


def conv_icon(path):
    im = Image.open(path).convert("RGBA")
    w, h = im.size
    fw = w // 2 if w >= 64 else w          # frame 0 = left half of the sheet
    frame = im.crop((0, 0, fw, h))
    frame = frame.resize((16, 16), Image.LANCZOS)
    px = frame.load()
    out = []
    for y in range(16):
        for x in range(16):
            r, g, b, a = px[x, y]
            out.append(0 if a < 128 else (0x8000 | rgb15(r, g, b)))
    return out


def main():
    spmap = species_map()
    index = [0xFFFF] * (MAX_INTERNAL + 1)
    data = []                # list of 256-int icons
    matched, skipped = 0, []

    for fn in sorted(os.listdir(ICONS)):
        if not fn.lower().endswith(".png"):
            continue
        stem = fn[:-4]
        if stem == "000":
            continue
        base = re.sub(r"_\d+$", "", stem)   # drop form variants (DEOXYS_1 ...)
        key = norm(base)
        intl = spmap.get(key)
        if intl is None:
            skipped.append(stem)
            continue
        if intl > MAX_INTERNAL or index[intl] != 0xFFFF:
            continue
        index[intl] = len(data)
        data.append(conv_icon(os.path.join(ICONS, fn)))
        matched += 1

    # --- emit .h ---
    with open(OUT_H, "w") as h:
        h.write("/* GENERATED by tools/gen_icons.py - do not edit. */\n")
        h.write("#ifndef MON_ICONS_H\n#define MON_ICONS_H\n#include <stdint.h>\n\n")
        h.write("#define MON_ICON_W 16\n#define MON_ICON_H 16\n")
        h.write("#define MON_ICON_NONE 0xFFFFu\n")
        h.write("#define MON_ICON_MAX_SPECIES %d\n\n" % MAX_INTERNAL)
        h.write("extern const uint16_t mon_icon_data[%d][256];\n" % len(data))
        h.write("extern const uint16_t mon_icon_index[%d];\n\n" % (MAX_INTERNAL + 1))
        h.write("/* 16x16 icon for an internal Gen-3 species id, or NULL if none. */\n")
        h.write("const uint16_t* mon_icon_for(uint16_t species);\n\n")
        h.write("#endif\n")

    # --- emit .c ---
    with open(OUT_C, "w") as c:
        c.write("/* GENERATED by tools/gen_icons.py - do not edit. */\n")
        c.write('#include "mon_icons.h"\n\n')
        c.write("const uint16_t mon_icon_data[%d][256] = {\n" % len(data))
        for icon in data:
            c.write("{")
            c.write(",".join("0x%04x" % v for v in icon))
            c.write("},\n")
        c.write("};\n\n")
        c.write("const uint16_t mon_icon_index[%d] = {\n" % (MAX_INTERNAL + 1))
        for i in range(0, MAX_INTERNAL + 1, 16):
            c.write(" " + ",".join("0x%04x" % index[j]
                    for j in range(i, min(i + 16, MAX_INTERNAL + 1))) + ",\n")
        c.write("};\n\n")
        c.write("const uint16_t* mon_icon_for(uint16_t species) {\n")
        c.write("  if (species > MON_ICON_MAX_SPECIES) return 0;\n")
        c.write("  uint16_t idx = mon_icon_index[species];\n")
        c.write("  return (idx == MON_ICON_NONE) ? 0 : mon_icon_data[idx];\n")
        c.write("}\n")

    print("icons matched: %d, data rows: %d" % (matched, len(data)))
    if skipped:
        print("unmatched (%d):" % len(skipped), ", ".join(skipped[:20]),
              "..." if len(skipped) > 20 else "")
    kb = len(data) * 256 * 2 / 1024
    print("icon data: %.1f KiB in ROM" % kb)


if __name__ == "__main__":
    main()
