#!/usr/bin/env python3
"""Convert the Gen-3 sprite-pack box icons into a 32x32 RGB15 blob (native
box-icon size — no extra downscaling).

For each species PNG (Graphics/Pokemon/Icons/<NAME>.png, a 128x64 sheet = two
64x64 frames) take frame 0, downscale to 32x32, and store each pixel as a u16:
  0x0000          -> transparent
  0x8000 | RGB15  -> opaque

Species are keyed by their INTERNAL Gen-3 id taken straight from the decomp
constants (SPECIES_KYOGRE=404 etc.) — the exact id the save stores; the old
national+25 shortcut mismapped the displaced legendaries (Kyogre->Registeel).

Emits (all git-ignored — ripped art, regenerate locally):
  data/mon_icons.bin          icons concatenated
  source/mon_icons_data.s     .incbin the blob into .rodata
  source/mon_icons.{c,h}      offset index + mon_icon_for()

Run from the repo root:  python3 tools/gen_icons.py   (needs Pillow)
"""
import os, re
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PACK = os.path.join(ROOT, "assets", "sprites", "Gen 3 Sprite Pack V1")
ICONS = os.path.join(PACK, "Graphics", "Pokemon", "Icons")
OUT_BIN = os.path.join(ROOT, "data", "mon_icons.bin")
OUT_S = os.path.join(ROOT, "source", "mon_icons_data.s")
OUT_C = os.path.join(ROOT, "source", "mon_icons.c")
OUT_H = os.path.join(ROOT, "source", "mon_icons.h")

SIZE = 32
MAX_INTERNAL = 411


def norm(s):
    return re.sub(r"[^A-Z0-9]", "", s.upper())


def species_map():
    path = os.path.join(ROOT, "reference", "pokeemerald_data", "include", "constants", "species.h")
    m = {}
    with open(path) as f:
        for line in f:
            mm = re.match(r"\s*#define\s+SPECIES_(\w+)\s+(\d+)", line)
            if mm:
                m[norm(mm.group(1))] = int(mm.group(2))
    if "NIDORANF" in m: m["NIDORANFE"] = m["NIDORANF"]
    if "NIDORANM" in m: m["NIDORANMA"] = m["NIDORANM"]
    return m


def conv(path):
    im = Image.open(path).convert("RGBA")
    w, h = im.size
    fw = w // 2 if w >= 64 else w            # frame 0 = left half of the sheet
    frame = im.crop((0, 0, fw, h)).resize((SIZE, SIZE), Image.LANCZOS)
    px = frame.load()
    out = bytearray()
    for y in range(SIZE):
        for x in range(SIZE):
            r, g, b, a = px[x, y]
            v = 0 if a < 128 else (0x8000 | (r >> 3) | ((g >> 3) << 5) | ((b >> 3) << 10))
            out += v.to_bytes(2, "little")
    return bytes(out)


def main():
    spmap = species_map()
    off = [0xFFFFFFFF] * (MAX_INTERNAL + 1)
    blob = bytearray()
    slot = 0
    for fn in sorted(os.listdir(ICONS)):
        if not fn.lower().endswith(".png"):
            continue
        stem = fn[:-4]
        if stem == "000":
            continue
        intl = spmap.get(norm(re.sub(r"_\d+$", "", stem)))
        if intl is None or intl > MAX_INTERNAL or off[intl] != 0xFFFFFFFF:
            continue
        off[intl] = slot * SIZE * SIZE * 2
        blob += conv(os.path.join(ICONS, fn))
        slot += 1

    os.makedirs(os.path.dirname(OUT_BIN), exist_ok=True)
    with open(OUT_BIN, "wb") as f:
        f.write(blob)

    with open(OUT_S, "w") as s:
        s.write("/* GENERATED by tools/gen_icons.py - do not edit. */\n")
        s.write("\t.section .rodata\n\t.align 2\n")
        s.write("\t.global mon_icon_blob\nmon_icon_blob:\n\t.incbin \"%s\"\n" % OUT_BIN)

    with open(OUT_H, "w") as h:
        h.write("/* GENERATED by tools/gen_icons.py - do not edit. */\n")
        h.write("#ifndef MON_ICONS_INCLUDED\n#define MON_ICONS_INCLUDED\n#include <stdint.h>\n\n")
        h.write("#define MON_ICON_W %d\n#define MON_ICON_H %d\n" % (SIZE, SIZE))
        h.write("#define MON_ICON_MAX_SPECIES %d\n\n" % MAX_INTERNAL)
        h.write("/* %dx%d icon (RGB15: 0 transparent, 0x8000|rgb opaque) for an internal\n" % (SIZE, SIZE))
        h.write("   Gen-3 species id, or NULL if none. */\n")
        h.write("const uint16_t* mon_icon_for(uint16_t species);\n\n#endif\n")

    with open(OUT_C, "w") as c:
        c.write("/* GENERATED by tools/gen_icons.py - do not edit. */\n")
        c.write('#include "mon_icons.h"\n\n')
        c.write("extern const uint8_t mon_icon_blob[];\n\n")
        c.write("static const uint32_t off_tbl[%d] = {\n" % (MAX_INTERNAL + 1))
        for i in range(0, MAX_INTERNAL + 1, 8):
            c.write("  " + ",".join("0x%08x" % off[j] for j in range(i, min(i + 8, MAX_INTERNAL + 1))) + ",\n")
        c.write("};\n\n")
        c.write("const uint16_t* mon_icon_for(uint16_t species) {\n")
        c.write("  if (species > %d) return 0;\n" % MAX_INTERNAL)
        c.write("  uint32_t o = off_tbl[species];\n")
        c.write("  if (o == 0xFFFFFFFFu) return 0;\n")
        c.write("  return (const uint16_t*)(mon_icon_blob + o);\n}\n")

    print("icons: %d species, %dx%d, %.1f KiB ROM" % (slot, SIZE, SIZE, len(blob) / 1024.0))


if __name__ == "__main__":
    main()
