#!/usr/bin/env python3
"""Convert the Gen-3 PC-storage hand cursor (frame 0) into a git-ignored RGB15
blob, exactly like gen_icons.py does for the box icons. Nintendo art is never
committed: the PNG lives under assets/ (git-ignored) and the generated
source/hand_cursor.{c,h} are git-ignored too.

Output format matches the icon/front-sprite convention used across the project:
  u16 pixel = 0x8000 | rgb15   (opaque)
            = 0x0000           (transparent)
so the existing per-pixel blit can skip 0 and plot the rest.
"""
import os
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC  = os.path.join(ROOT, "assets", "storage", "hand_cursor.png")
OUTC = os.path.join(ROOT, "source", "hand_cursor.c")
OUTH = os.path.join(ROOT, "source", "hand_cursor.h")


def rgb15(r, g, b):
    return (r >> 3) | ((g >> 3) << 5) | ((b >> 3) << 10)


def main():
    im = Image.open(SRC)
    if im.mode != "P":
        im = im.convert("P")
    pal = im.getpalette()
    px = im.load()
    W, H = im.size
    FRAME = 32                      # the sheet is 32-wide, 32-tall frames stacked
    px0 = [[px[x, y] for x in range(FRAME)] for y in range(FRAME)]

    # tight bounding box of the non-transparent (index != 0) pixels of frame 0
    xs = [x for y in range(FRAME) for x in range(FRAME) if px0[y][x] != 0]
    ys = [y for y in range(FRAME) for x in range(FRAME) if px0[y][x] != 0]
    x0, x1 = min(xs), max(xs)
    y0, y1 = min(ys), max(ys)
    w, h = x1 - x0 + 1, y1 - y0 + 1

    rows = []
    for y in range(y0, y1 + 1):
        vals = []
        for x in range(x0, x1 + 1):
            idx = px0[y][x]
            if idx == 0:
                vals.append(0)
            else:
                r, g, b = pal[idx * 3], pal[idx * 3 + 1], pal[idx * 3 + 2]
                vals.append(0x8000 | rgb15(r, g, b))
        rows.append(vals)

    with open(OUTH, "w") as f:
        f.write("/* GENERATED by tools/gen_hand.py - do not edit, do not commit. */\n")
        f.write("#ifndef HAND_CURSOR_INCLUDED\n#define HAND_CURSOR_INCLUDED\n")
        f.write("#include <stdint.h>\n")
        f.write(f"#define HAND_W {w}\n#define HAND_H {h}\n")
        f.write("extern const uint16_t hand_cursor[HAND_W * HAND_H];\n")
        f.write("#endif\n")

    with open(OUTC, "w") as f:
        f.write("/* GENERATED by tools/gen_hand.py - do not edit, do not commit. */\n")
        f.write('#include "hand_cursor.h"\n\n')
        f.write("const uint16_t hand_cursor[HAND_W * HAND_H] = {\n")
        for vals in rows:
            f.write("  " + ",".join("0x%04X" % v for v in vals) + ",\n")
        f.write("};\n")

    print(f"hand_cursor: frame0 bbox ({x0},{y0})-({x1},{y1}) -> {w}x{h}")


if __name__ == "__main__":
    main()
