#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Generate source/gb1_base_gen.c -- the Gen-1 base-stat + type + growth table for all
151 species (BACKLOG #276), so CREATE > FROM SCRATCH on a Game Boy (Gen 1) save needs no
ROM read for its base row.

WHY: Gen 1's Special base differs from Gen 3's SpA for 43 species and its type ids are a
different numbering (Fire is 0x14), so source/ has no in-tree Gen-1 table (gb_edit.h says
so). PokeDNA ships no Game Freak data; like source/data_tables.c this file is GENERATED
from the reference decomp on the developer's machine and GIT-IGNORED. A clone without it
still links (source/gb1_base_fallback.c is the committed weak default: "no table"), and
the scratch arm falls back to the ROM read it used before.

CLEAN-ROOM: assets/upstream/pokered is REFERENCE ONLY. This script reads NUMBERS out of
data/pokemon/base_stats/*.asm (HP/Atk/Def/Spd/Spc, the two type ids, the growth-rate id)
and the constants files that name them; it copies no code, no prose, no names.

Row layout emitted (8 bytes, indexed by national dex - 1):
    hp, atk, def, spe, spc, type1, type2, growth
Type ids are RAW Gen-1 ids (0x00-0x08 physical, 0x14-0x1A special); growth is 0..5
(gen1_write.h GEN1_GROWTH_*). All three id spaces are DERIVED from pokered's own
const_def/const/const_next counters, not typed here.

    python3 tools/gen_gb1_base.py            # writes source/gb1_base_gen.c
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MAIN = "/Users/guyshtainer/VSCodeProjects/gba-toolkit/projects/PokeDNA"   # lane worktrees carry no assets/upstream
UP = os.environ.get("POKERED", os.path.join(ROOT, "assets", "upstream", "pokered"))
if not os.path.isdir(UP):
    UP = os.path.join(MAIN, "assets", "upstream", "pokered")
OUT = os.path.join(ROOT, "source", "gb1_base_gen.c")


def read(rel):
    with open(os.path.join(UP, rel), encoding="utf-8") as f:
        return f.read()


def const_table(text, start_marker=None):
    """Replay RGBDS const_def/const/const_next: name -> value for every `const NAME`."""
    val, out = 0, {}
    for raw in text.splitlines():
        ln = raw.split(";")[0].strip()
        m = re.match(r"const_def(?:\s+(\S+))?", ln)
        if m:
            val = int(m.group(1), 0) if m.group(1) else 0
            continue
        m = re.match(r"const_next\s+(\S+)", ln)
        if m:
            val = int(m.group(1), 0)
            continue
        m = re.match(r"const\s+(\w+)$", ln)
        if m:
            out[m.group(1)] = val
            val += 1
    return out


def main():
    dex = const_table(read("constants/pokedex_constants.asm"))
    types = const_table(read("constants/type_constants.asm"))
    growth = const_table(read("constants/pokemon_data_constants.asm"))
    rows = {}
    d = os.path.join(UP, "data", "pokemon", "base_stats")
    for fn in sorted(os.listdir(d)):
        if not fn.endswith(".asm"):
            continue
        dbs = [ln.split(";")[0].strip() for ln in read(f"data/pokemon/base_stats/{fn}").splitlines()]
        dbs = [ln[2:].strip() for ln in dbs if ln.startswith("db ")]
        # order in every file: dex id, 5 stats, 2 types, catch, exp, ...; growth is the
        # `db GROWTH_*` line
        n = dex[dbs[0]]
        stats = [int(x) for x in dbs[1].split(",")]
        t = [x.strip() for x in dbs[2].split(",")]
        g = next(x for x in dbs if x.startswith("GROWTH_"))
        assert len(stats) == 5 and len(t) == 2, fn
        assert 1 <= n <= 151 and n not in rows, (fn, n)
        rows[n] = stats + [types[t[0]], types[t[1]], growth[g]]
    assert sorted(rows) == list(range(1, 152)), "need exactly dex 1..151"
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("/* GENERATED by tools/gen_gb1_base.py -- do not edit; git-ignored (BACKLOG #276).\n"
                " * Gen-1 base stats (hp atk def spe spc), raw Gen-1 type ids and growth id per\n"
                " * national dex 1..151, numbers only. */\n"
                "#include \"gb1_base_tbl.h\"\n\n"
                "static const uint8_t k_rows[151][GB1_BASE_ROW_LEN] = {\n")
        for n in range(1, 152):
            f.write("  {" + ",".join(str(x) for x in rows[n]) + "},\n")
        f.write("};\n\n"
                "bool gb1_base_gen_row(uint16_t dex, uint8_t out[GB1_BASE_ROW_LEN]) {\n"
                "  if (dex < 1 || dex > 151 || !out) return false;\n"
                "  for (int i = 0; i < GB1_BASE_ROW_LEN; i++) out[i] = k_rows[dex - 1][i];\n"
                "  return true;\n}\n")
    print(f"wrote {OUT}: 151 rows, {os.path.getsize(OUT)} bytes")


if __name__ == "__main__":
    sys.exit(main())
