#!/usr/bin/env python3
"""Convert the Gen-3 item icons (pret/pokeemerald) into a git-ignored 24x24 RGB15
blob indexed by save-file ITEM ID (0..376), like gen_icons.py for box icons.

Item icons are a TWO-part asset: each item id maps (via item_icon_table.h) to a
{pic, palette} pair, and the pic + palette are decoupled (one PNG is reused with
different palettes — e.g. the flutes). So the PNG's own palette is NOT used; the
true colors come from the EXTERNAL .pal named in the table. We dedupe on the
(png, pal) pair to keep the blob small.

Inputs (downloaded under assets/items/, git-ignored): meta/{item_icon_table.h,
graphics_items.h, items_constants.h}, icons/<name>.png, icon_palettes/<name>.pal.

Emits (all git-ignored — ripped art, regenerate locally):
  data/item_icons.bin       icons concatenated
  source/item_icons_data.s  .incbin the blob into .rodata
  source/item_icons.{c,h}   id->offset index + item_icon_for()

Pixel convention: 0x0000 transparent (palette index 0) / 0x8000|rgb15 opaque.
"""
import os, re
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
A = os.path.join(ROOT, "assets", "items")
META = os.path.join(A, "meta")
OUT_BIN = os.path.join(ROOT, "data", "item_icons.bin")
OUT_S = os.path.join(ROOT, "source", "item_icons_data.s")
OUT_C = os.path.join(ROOT, "source", "item_icons.c")
OUT_H = os.path.join(ROOT, "source", "item_icons.h")

SIZE = 24
MAX_ID = 376


def parse_meta():
    ids = {}
    for line in open(os.path.join(META, "items_constants.h")):
        m = re.match(r"\s*#define\s+(ITEM_\w+)\s+(\d+)\b", line)
        if m:
            ids[m.group(1)] = int(m.group(2))
    table = {}
    for line in open(os.path.join(META, "item_icon_table.h")):
        m = re.search(r"\[(ITEM_\w+)\]\s*=\s*\{\s*(gItemIcon_\w+)\s*,\s*(gItemIconPalette_\w+)\s*\}", line)
        if m:
            table[m.group(1)] = (m.group(2), m.group(3))
    sym = {}
    for m in re.finditer(r'const u32 (g\w+)\[\]\s*=\s*INCGFX_U32\("([^"]+)"', open(os.path.join(META, "graphics_items.h")).read()):
        sym[m.group(1)] = os.path.basename(m.group(2))
    idmap = {}
    for name, (pic, pal) in table.items():
        iid = ids.get(name)
        if iid is None or pic not in sym or pal not in sym:
            continue
        idmap[iid] = (sym[pic], sym[pal])
    return idmap


def read_pal(name):
    """JASC-PAL -> list of 16 (r,g,b)."""
    lines = open(os.path.join(A, "icon_palettes", name)).read().split("\n")
    cols = []
    for ln in lines[3:]:
        ln = ln.strip()
        if not ln:
            continue
        r, g, b = (int(v) for v in ln.split()[:3])
        cols.append((r, g, b))
        if len(cols) == 16:
            break
    while len(cols) < 16:
        cols.append((0, 0, 0))
    return cols


def render(png, pal):
    im = Image.open(os.path.join(A, "icons", png))
    if im.mode != "P":
        im = im.convert("P")
    px = im.load()
    w, h = im.size
    cols = read_pal(pal)
    out = bytearray()
    for y in range(SIZE):
        for x in range(SIZE):
            if x < w and y < h:
                idx = px[x, y]
            else:
                idx = 0
            if idx == 0:
                v = 0
            else:
                r, g, b = cols[idx]
                v = 0x8000 | (r >> 3) | ((g >> 3) << 5) | ((b >> 3) << 10)
            out += v.to_bytes(2, "little")
    return bytes(out)


def main():
    idmap = parse_meta()
    off = [0xFFFFFFFF] * (MAX_ID + 1)
    blob = bytearray()
    pair_slot = {}                 # (png,pal) -> byte offset (dedupe)
    for iid in range(MAX_ID + 1):
        pair = idmap.get(iid)
        if pair is None:
            continue
        if pair not in pair_slot:
            pair_slot[pair] = len(blob)
            blob += render(pair[0], pair[1])
        off[iid] = pair_slot[pair]

    os.makedirs(os.path.dirname(OUT_BIN), exist_ok=True)
    with open(OUT_BIN, "wb") as f:
        f.write(blob)

    with open(OUT_S, "w") as s:
        s.write("/* GENERATED by tools/gen_items.py - do not edit, do not commit. */\n")
        s.write("\t.section .rodata\n\t.align 2\n")
        s.write('\t.global item_icon_blob\nitem_icon_blob:\n\t.incbin "%s"\n' % OUT_BIN)

    with open(OUT_H, "w") as h:
        h.write("/* GENERATED by tools/gen_items.py - do not edit, do not commit. */\n")
        h.write("#ifndef ITEM_ICONS_INCLUDED\n#define ITEM_ICONS_INCLUDED\n#include <stdint.h>\n\n")
        h.write("#define ITEM_ICON_W %d\n#define ITEM_ICON_H %d\n" % (SIZE, SIZE))
        h.write("#define ITEM_ICON_MAX_ID %d\n\n" % MAX_ID)
        h.write("/* 24x24 RGB15 icon (0 transparent / 0x8000|rgb opaque) for an item id,\n")
        h.write("   or NULL if the id has no icon. */\n")
        h.write("const uint16_t* item_icon_for(uint16_t item_id);\n\n#endif\n")

    with open(OUT_C, "w") as c:
        c.write("/* GENERATED by tools/gen_items.py - do not edit, do not commit. */\n")
        c.write('#include "item_icons.h"\n\n')
        c.write("extern const uint8_t item_icon_blob[];\n\n")
        c.write("static const uint32_t off_tbl[%d] = {\n" % (MAX_ID + 1))
        for i in range(0, MAX_ID + 1, 8):
            c.write("  " + ",".join("0x%08x" % off[j] for j in range(i, min(i + 8, MAX_ID + 1))) + ",\n")
        c.write("};\n\n")
        c.write("const uint16_t* item_icon_for(uint16_t item_id) {\n")
        c.write("  if (item_id > %d) return 0;\n" % MAX_ID)
        c.write("  uint32_t o = off_tbl[item_id];\n")
        c.write("  if (o == 0xFFFFFFFFu) return 0;\n")
        c.write("  return (const uint16_t*)(item_icon_blob + o);\n}\n")

    print("items: %d ids, %d unique icons, %dx%d, %.1f KiB ROM" %
          (sum(1 for o in off if o != 0xFFFFFFFF), len(pair_slot), SIZE, SIZE, len(blob) / 1024.0))


if __name__ == "__main__":
    main()
