#!/usr/bin/env python3
"""Convert the Gen-3 PC-storage hand cursor into git-ignored RGB15 blobs, exactly
like gen_icons.py does for the box icons. Nintendo art is never committed: the PNG
lives under assets/ (git-ignored) and the generated source/hand_cursor.{c,h} are
git-ignored too.

The sheet is 32 wide and holds four 32x32 frames stacked vertically:
  frame 0  open hand   -> the resting PC cursor          (hand_cursor[])
  frame 2  wide reach  -> mid grab-animation pose         (hand_reach[])
  frame 3  closed fist -> the "grabbing / carrying" pose  (hand_grab[])
We extract the three we use for the pick-up animation (open -> reach -> grab), each
tightly bounding-boxed with its own W/H.

Output format matches the icon/front-sprite convention used across the project:
  u16 pixel = 0x8000 | rgb15   (opaque)
            = 0x0000           (transparent)
so the existing per-pixel blit can skip 0 and plot the rest.
"""
import os
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC  = os.path.join(ROOT, "assets", "storage", "hand_cursor.png")
OUTC = os.path.join(ROOT, "source", "hand_cursor.c")
OUTH = os.path.join(ROOT, "source", "hand_cursor.h")

FRAME = 32
# (frame index in the sheet, C identifier, H-macro prefix)
WANT = [(0, "hand_cursor", "HAND"),
        (2, "hand_reach",  "HAND_REACH"),
        (3, "hand_grab",   "HAND_GRAB")]


def rgb15(r, g, b):
    return (r >> 3) | ((g >> 3) << 5) | ((b >> 3) << 10)


def extract(px, pal, fr):
    """Tight-bbox one 32x32 frame -> (w, h, rows[list[list[u16]]])."""
    y0base = fr * FRAME
    grid = [[px[x, y0base + y] for x in range(FRAME)] for y in range(FRAME)]
    xs = [x for y in range(FRAME) for x in range(FRAME) if grid[y][x] != 0]
    ys = [y for y in range(FRAME) for x in range(FRAME) if grid[y][x] != 0]
    x0, x1 = min(xs), max(xs)
    y0, y1 = min(ys), max(ys)
    rows = []
    for y in range(y0, y1 + 1):
        vals = []
        for x in range(x0, x1 + 1):
            idx = grid[y][x]
            if idx == 0:
                vals.append(0)
            else:
                r, g, b = pal[idx * 3], pal[idx * 3 + 1], pal[idx * 3 + 2]
                vals.append(0x8000 | rgb15(r, g, b))
        rows.append(vals)
    return (x1 - x0 + 1, y1 - y0 + 1, rows)


def main():
    im = Image.open(SRC)
    if im.mode != "P":
        im = im.convert("P")
    pal = im.getpalette()
    px = im.load()

    # WHITE glove: the source is a yellow/orange glove (fill indices 3, 11, 12)
    # with a dark/light outline (indices 1, 2). Remap only the fill to white so
    # we keep the outline — pokeemerald ships no white cursor frame.
    for i in (3, 11, 12):
        pal[i * 3], pal[i * 3 + 1], pal[i * 3 + 2] = 255, 255, 255

    frames = [(name, pref, extract(px, pal, fr)) for fr, name, pref in WANT]

    with open(OUTH, "w") as f:
        f.write("/* GENERATED by tools/gen_hand.py - do not edit, do not commit. */\n")
        f.write("#ifndef HAND_CURSOR_INCLUDED\n#define HAND_CURSOR_INCLUDED\n")
        f.write("#include <stdint.h>\n")
        for name, pref, (w, h, _rows) in frames:
            f.write(f"#define {pref}_W {w}\n#define {pref}_H {h}\n")
            f.write(f"extern const uint16_t {name}[{pref}_W * {pref}_H];\n")
        f.write("#endif\n")

    with open(OUTC, "w") as f:
        f.write("/* GENERATED by tools/gen_hand.py - do not edit, do not commit. */\n")
        f.write('#include "hand_cursor.h"\n\n')
        for name, pref, (w, h, rows) in frames:
            f.write(f"const uint16_t {name}[{pref}_W * {pref}_H] = {{\n")
            for vals in rows:
                f.write("  " + ",".join("0x%04X" % v for v in vals) + ",\n")
            f.write("};\n\n")

    for name, pref, (w, h, _rows) in frames:
        print(f"{name}: {w}x{h}")


if __name__ == "__main__":
    main()
