#!/usr/bin/env python3
"""Convert the Gen-3 sprite-pack FRONT sprites (normal + shiny) into a 64x64
RGB15 blob for the summary / box data panel.

For each species PNG (Graphics/Pokemon/Front/<NAME>.png and Front shiny/<NAME>.png)
downscale to 64x64 and store each pixel as a u16:
  0x0000          -> transparent
  0x8000 | RGB15  -> opaque
Both blobs share one index (same species at the same byte offset), so a single
offset table works for normal and shiny.

Emits (all git-ignored — ripped art, generate locally):
  data/mon_front.bin            normal sprites, concatenated
  data/mon_front_shiny.bin      shiny sprites, concatenated
  source/mon_front_data.s       .incbin the two blobs into .rodata
  source/mon_front.c            offset table + mon_front_for()

Run from the repo root:  python3 tools/gen_front.py   (needs Pillow)
"""
import os, re
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PACK = os.path.join(ROOT, "assets", "sprites", "Gen 3 Sprite Pack V1")
FRONT = os.path.join(PACK, "Graphics", "Pokemon", "Front")
SHINY = os.path.join(PACK, "Graphics", "Pokemon", "Front shiny")
PBS = os.path.join(PACK, "PBS", "pokemon_metrics.txt")
OUT_BIN = os.path.join(ROOT, "data", "mon_front.bin")
OUT_BIN_S = os.path.join(ROOT, "data", "mon_front_shiny.bin")
OUT_S = os.path.join(ROOT, "source", "mon_front_data.s")
OUT_C = os.path.join(ROOT, "source", "mon_front.c")

SIZE = 64          # full-size front sprite
MAX_INTERNAL = 411
# Only the NORMAL sprite blob is shipped: a second 64x64 shiny blob (~3MB) would
# push the ROM past the EZ-Flash PSRAM ceiling. Shiny mons show the normal sprite
# (plus the shiny * marker); mon_front_for() ignores the `shiny` arg.


def norm(s):
    return re.sub(r"[^A-Z0-9]", "", s.upper())


def species_map():
    """norm(species name) -> INTERNAL Gen-3 id, straight from the decomp constants
    (SPECIES_KYOGRE=404 etc.). This is the EXACT mapping the save uses; the old
    national+25 shortcut mismapped the displaced legendaries (Kyogre->Registeel)."""
    path = os.path.join(ROOT, "reference", "pokeemerald_data", "include", "constants", "species.h")
    m = {}
    with open(path) as f:
        for line in f:
            mm = re.match(r"\s*#define\s+SPECIES_(\w+)\s+(\d+)", line)
            if mm:
                m[norm(mm.group(1))] = int(mm.group(2))
    if "NIDORANF" in m: m["NIDORANFE"] = m["NIDORANF"]   # PNG NIDORANfE -> SPECIES_NIDORAN_F
    if "NIDORANM" in m: m["NIDORANMA"] = m["NIDORANM"]   # PNG NIDORANmA -> SPECIES_NIDORAN_M
    return m


def conv(path):
    im = Image.open(path).convert("RGBA").resize((SIZE, SIZE), Image.LANCZOS)
    im = im.transpose(Image.FLIP_LEFT_RIGHT)    # face left, like the in-game summary sprite
    px = im.load()
    out = bytearray()
    for y in range(SIZE):
        for x in range(SIZE):
            r, g, b, a = px[x, y]
            v = 0 if a < 128 else (0x8000 | (r >> 3) | ((g >> 3) << 5) | ((b >> 3) << 10))
            out += v.to_bytes(2, "little")
    return bytes(out)


def main():
    spmap = species_map()
    off = [0xFFFFFFFF] * (MAX_INTERNAL + 1)
    normal = bytearray()
    slot = 0

    for fn in sorted(os.listdir(FRONT)):
        if not fn.lower().endswith(".png"):
            continue
        stem = fn[:-4]
        if stem == "000":
            continue
        key = norm(re.sub(r"_\d+$", "", stem))
        intl = spmap.get(key)
        if intl is None or intl > MAX_INTERNAL or off[intl] != 0xFFFFFFFF:
            continue
        off[intl] = slot * SIZE * SIZE * 2
        normal += conv(os.path.join(FRONT, fn))
        slot += 1

    os.makedirs(os.path.dirname(OUT_BIN), exist_ok=True)
    with open(OUT_BIN, "wb") as f:
        f.write(normal)

    with open(OUT_S, "w") as s:
        s.write("/* GENERATED by tools/gen_front.py - do not edit. */\n")
        s.write("\t.section .rodata\n\t.align 2\n")
        # absolute path: the assembler runs from build/, and this .s is git-ignored / regenerated locally
        s.write("\t.global mon_front_blob\nmon_front_blob:\n\t.incbin \"%s\"\n" % OUT_BIN)

    with open(OUT_C, "w") as c:
        c.write("/* GENERATED by tools/gen_front.py - do not edit. */\n")
        c.write('#include "mon_front.h"\n\n')
        c.write("extern const uint8_t mon_front_blob[];\n\n")
        c.write("static const uint32_t off_tbl[%d] = {\n" % (MAX_INTERNAL + 1))
        for i in range(0, MAX_INTERNAL + 1, 8):
            row = ",".join("0x%08x" % off[j] for j in range(i, min(i + 8, MAX_INTERNAL + 1)))
            c.write("  " + row + ",\n")
        c.write("};\n\n")
        c.write("/* shiny arg ignored — only the normal blob is shipped (ROM/PSRAM budget). */\n")
        c.write("const uint16_t* mon_front_for(uint16_t species, bool shiny) {\n")
        c.write("  (void)shiny;\n")
        c.write("  if (species > %d) return 0;\n" % MAX_INTERNAL)
        c.write("  uint32_t o = off_tbl[species];\n")
        c.write("  if (o == 0xFFFFFFFFu) return 0;\n")
        c.write("  return (const uint16_t*)(mon_front_blob + o);\n")
        c.write("}\n")

    kb = len(normal) / 1024.0
    print("front sprites: %d species, %.2f MiB ROM (normal only, %dx%d)"
          % (slot, kb / 1024.0, SIZE, SIZE))


if __name__ == "__main__":
    main()
