#!/usr/bin/env python3
"""Generate source/daycare_bg_data.h — the Day-Care yard background for the daycare
scene, converted from a user-supplied template image (a Gen-3-style overworld yard
with lava / ponds / a rocky hill / a power line / the day-care house).

The daycare screen blits this into the scene region (screen y 12..123, full width)
and places the boarding Pokemon by type onto matching terrain (lava / hill / water /
top-right power line / grass). The image is cropped to the fenced yard (the grassy
path below the fence is dropped) and scaled to 240x112; each pixel becomes raw
BGR555 (no opacity bit — it is an opaque background, DMA'd straight to VRAM).

Output is GIT-IGNORED (generate-locally policy, same as mon_front.c / wallpapers.c):
the public source ships no art; the daycare falls back to a procedural scene when
this header is absent (see source/pdna_main.c, #ifdef HAVE_DAYCARE_BG).

Run from the project root:
    python3 tools/gen_daycare_bg.py ["/path/to/template.png"]
The default source is the template the user provided in ~/Downloads.
"""
import os, sys
from PIL import Image

OUT_W, OUT_H = 240, 112          # scene region (screen y 12..123)
CROP_FRAC    = 0.72              # keep the fenced yard; drop the path below the fence

DEFAULT_SRC = os.path.expanduser(
    "~/Downloads/ChatGPT Image Jun 21, 2026, 12_34_14 PM.png")

# placement region centers in OUTPUT (240x112) pixel coords, kept in sync with
# DC_REGION[] in source/pdna_main.c. (screen y = 12 + these y.)
REGIONS = {
    "lava":  (53, 31),
    "hill":  (55, 93),
    "water": (115, 31),
    "elec":  (199, 28),
    "grass": (108, 70),
}


def to_bgr555(r, g, b):
    return (r >> 3) | ((g >> 3) << 5) | ((b >> 3) << 10)


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_SRC
    if not os.path.exists(src):
        sys.exit("source image not found: %s\n(pass the path as an argument)" % src)
    im = Image.open(src).convert("RGB")
    W, H = im.size
    im = im.crop((0, 0, W, int(H * CROP_FRAC)))          # drop the path below the fence
    im = im.resize((OUT_W, OUT_H), Image.LANCZOS)
    px = im.load()

    vals = []
    for y in range(OUT_H):
        for x in range(OUT_W):
            r, g, b = px[x, y]
            vals.append(to_bgr555(r, g, b))

    out = os.path.join(os.path.dirname(__file__), "..", "source", "daycare_bg_data.h")
    out = os.path.normpath(out)
    with open(out, "w") as f:
        f.write("/* GENERATED by tools/gen_daycare_bg.py - do not edit. GIT-IGNORED. */\n")
        f.write("#ifndef DAYCARE_BG_DATA_H\n#define DAYCARE_BG_DATA_H\n")
        f.write("#define DAYCARE_BG_W %d\n#define DAYCARE_BG_H %d\n" % (OUT_W, OUT_H))
        # aligned(4): the daycare blits it with 32-bit DMA (needs a word-aligned source)
        f.write("static const unsigned short __attribute__((aligned(4)))\n"
                "  daycare_bg[DAYCARE_BG_W*DAYCARE_BG_H] = {\n")
        for i in range(0, len(vals), 16):
            f.write("  " + ",".join("0x%04x" % v for v in vals[i:i + 16]) + ",\n")
        f.write("};\n#endif\n")

    # sanity: report the colour at each placement region so the mapping can be checked
    print("wrote %s  (%dx%d, %d px)" % (out, OUT_W, OUT_H, len(vals)))
    for name, (rx, ry) in REGIONS.items():
        r, g, b = px[rx, ry]
        print("  region %-6s (%3d,%3d) -> RGB(%3d,%3d,%3d)" % (name, rx, ry, r, g, b))


if __name__ == "__main__":
    main()
