#!/usr/bin/env python3
"""Paged GBA-LZ77 packing for the full-screen RGB15 art blobs.

WHY THIS EXISTS
---------------
The trainer card, bag and Pokeblock-case blobs are pre-composited 240x160
RGB15 frames, stored RAW. They are flat game art, so they compress ~7x with
the GBA BIOS's own LZ77 — and they were 5.7 MB of a 12.5 MB ROM. A 12.5 MB
file on the EZ-Flash Omega DE occupies enough clusters that it is regularly
fragmented past the kernel's unbounded FAT run-table (projects/rom-load-lab),
which hangs the loader at "LOADING GAME" while the same image boots fine from
NOR. Fewer bytes = fewer clusters = fewer chances to fragment.

Whole-blob LZ77 is useless here: the accessors hand out POINTERS into the blob
and the UI restores small rects out of the middle of a frame on every cursor
move. So the blob is split into fixed PAGES, each compressed on its own, with
a u32 offset table. The console decompresses only the pages a blit or a rect
restore actually touches (source/lzblob.c).

PAGE SIZE: 3840 B = 240 px x 8 rows of RGB15.
  * A page is exactly 8 full screen rows, so a page-aligned full-screen blit
    decompresses 20 pages straight into VRAM with no intermediate buffer.
  * A PARTIAL rect restore has to stage a page somewhere, and there were only
    1508 bytes of EWRAM left. 3840 B is what fits the one region that belongs
    to nobody: the gap between the end of the Mode-3 framebuffer (0x06012C00)
    and bitmap-mode OBJ tile 512 (0x06014000) — 5120 B of VRAM. So the whole
    scheme costs ZERO EWRAM. See source/lzblob.c.
  * The LZ77 window is only 4096 B, so paging costs little: measured on
    data/card_bg.bin, whole-frame 7.49x vs 8-row pages 6.79x.

The packed stream is plain GBA BIOS LZ77 (type 0x10) per page, so the console
side is a BIOS call, not our own decoder.
"""

import os
import struct
import subprocess
import tempfile

PAGE = 3840                      # 240 px * 8 rows * 2 B — see the docstring


def _gbalzss():
    """devkitPro's gbalzss, which emits exactly what the BIOS decodes."""
    for p in (os.path.join(os.environ.get("DEVKITPRO", "/opt/devkitpro"),
                           "tools", "bin", "gbalzss"),
              "gbalzss"):
        if p == "gbalzss" or os.path.exists(p):
            return p
    raise SystemExit("gbalzss not found — set DEVKITPRO")


def lz77(raw):
    """Compress one page to BIOS LZ77 (type 0x10)."""
    exe = _gbalzss()
    with tempfile.NamedTemporaryFile(delete=False) as f:
        f.write(raw)
        src = f.name
    dst = src + ".lz"
    try:
        subprocess.run([exe, "e", src, dst], check=True, capture_output=True)
        with open(dst, "rb") as f:
            return f.read()
    finally:
        for p in (src, dst):
            if os.path.exists(p):
                os.unlink(p)


def pad(raw):
    """Round a blob up to a whole number of pages.

    The console decompresses a whole page at a time into a fixed 3840-byte
    scratch, so a short final page would both under-fill the scratch and make
    the fast path's "h is a whole number of pages" test a lie. Zero padding
    costs ~20 compressed bytes.
    """
    n = (-len(raw)) % PAGE
    return raw + b"\0" * n


def pack(raw):
    """raw bytes -> (packed bytes, [npages+1 u32 offsets into packed]).

    Every page is 4-byte aligned because the BIOS LZ77 reader requires it.
    The table carries a trailing end offset so a page's compressed length is
    always offs[i+1]-offs[i] — the console never needs a length table.
    """
    raw = pad(raw)
    out = bytearray()
    offs = []
    for base in range(0, len(raw), PAGE):
        while len(out) & 3:
            out.append(0)
        offs.append(len(out))
        out += lz77(raw[base:base + PAGE])
    while len(out) & 3:
        out.append(0)
    offs.append(len(out))
    return bytes(out), offs


def emit(raw, out_bin, name, out_s, gen):
    """Pack `raw`, write the packed blob + its .incbin stub, return the C text
    that declares the page table and the LzBlob descriptor for it."""
    packed, offs = pack(raw)
    os.makedirs(os.path.dirname(out_bin), exist_ok=True)
    with open(out_bin, "wb") as f:
        f.write(packed)

    with open(out_s, "w") as f:
        f.write("/* GENERATED by tools/%s - do not edit, do not commit. */\n"
                "\t.section .rodata\n"
                "\t.balign 4\n"
                "\t.global %s_lz\n"
                "%s_lz:\n"
                "\t.incbin \"%s\"\n" % (gen, name, name, out_bin))

    # The page size is agreed between this packer and source/lzblob.h. A stale
    # copy on either side does not fail loudly — it silently unpacks the wrong
    # page and paints garbage on exactly the screens that use the staged path
    # (this happened once, and only a framebuffer probe caught it). So every
    # generated table asserts the pair at compile time.
    c = ['_Static_assert(LZBLOB_PAGE == %du,\n'
         '               "tools/lzband.py packed %s at a different page size than '
         'source/lzblob.h reads");\n' % (PAGE, name),
         'extern const uint8_t %s_lz[];\n' % name,
         'static const uint32_t %s_pages[%d] = {\n' % (name, len(offs))]
    for i in range(0, len(offs), 8):
        c.append("  " + ",".join("%du" % v for v in offs[i:i + 8]) + ",\n")
    c.append("};\n"
             "static const LzBlob %s_blob = { %s_lz, %s_pages, %du, %du };\n\n"
             % (name, name, name, len(offs) - 1, (len(offs) - 1) * PAGE))
    return "".join(c), len(packed)


def report(label, raw_len, packed_len):
    print("  %-18s %9d -> %8d B  (%.2fx, saved %d)"
          % (label, raw_len, packed_len, raw_len / max(packed_len, 1),
             raw_len - packed_len))


if __name__ == "__main__":                       # measurement helper
    import sys
    for p in sys.argv[1:]:
        raw = open(p, "rb").read()
        packed, offs = pack(raw)
        report(os.path.basename(p), len(raw), len(packed))
