/* Committed API header. The retail hand tiles (hand_oam.c) are generated by
 * tools/gen_hand_oam.py and git-ignored; an art-free build links the ORIGINAL
 * pointer cursor from art_fallbacks.c (weak symbols) instead. */
#ifndef HAND_OAM_INCLUDED
#define HAND_OAM_INCLUDED
#include <stdint.h>

#define HAND_OAM_TILES 16   /* 32x32 sprite = 16 4bpp tiles */
#define HAND_OAM_TILE_BYTES 32

extern const uint8_t  hand_oam_cursor_tiles[HAND_OAM_TILES * HAND_OAM_TILE_BYTES];
extern const uint8_t  hand_oam_reach_tiles[HAND_OAM_TILES * HAND_OAM_TILE_BYTES];
extern const uint8_t  hand_oam_grab_tiles[HAND_OAM_TILES * HAND_OAM_TILE_BYTES];
extern const uint16_t hand_oam_pal[16];  /* slot 0 transparent */

#endif
