/* Committed API header. The DATA (item_icons.c + blob) is generated by
 * tools/gen_items.py and git-ignored; art-free builds get NULL from
 * art_fallbacks.c and the screens keep their text layouts. */
#ifndef ITEM_ICONS_INCLUDED
#define ITEM_ICONS_INCLUDED
#include <stdint.h>

#define ITEM_ICON_W 24
#define ITEM_ICON_H 24
#define ITEM_ICON_MAX_ID 376

/* 24x24 RGB15 icon (0 transparent / 0x8000|rgb opaque) for an item id,
   or NULL if the id has no icon. */
const uint16_t* item_icon_for(uint16_t item_id);

#endif
