#ifndef LEARNSETS_H
#define LEARNSETS_H

#include <stdint.h>
#include <stdbool.h>

/* Generated by tools/gen_legality.py (source/learnsets.c, git-ignored).
 *
 * Per-species "could this species line EVER learn this move?" bitset. True for a
 * move that some Gen-3 method teaches the species or any of its pre-evolutions:
 *   level-up + egg moves over the whole pre-evolution chain, PLUS every TM/HM
 *   and move-tutor move (over-accepted for all species).
 *
 * Conservative by design: TM/HM/tutor are accepted for every species, so a legit
 * mon never gets flagged (zero false positives). A `false` therefore means NO
 * Gen-3 method teaches that move to the line — a signature move on the wrong
 * species or a later-generation move. The legality checker reports such moves as
 * WARNINGS, never a hard "illegal". Unknown species/move ids return true. */
bool pk_can_learn(uint16_t species, uint16_t move);

#endif /* LEARNSETS_H */
