#ifndef LEARNSETS2_H
#define LEARNSETS2_H

#include <stdint.h>
#include <stdbool.h>
#include "gen3_trainer.h"   /* PkGame: PK_RS / PK_EMERALD / PK_FRLG */

/* Per-game-group move-source data WITH LEARN LEVELS — the Legality-V2 upgrade of
 * learnsets.h (docs/research-legality-v2.md §3 C2-C5, §4 T_levelup/T_tmhm/
 * T_tutor/T_eggmoves). Tables are generated by tools/gen_learnsets2.py into
 * source/learnsets2.c, which is git-ignored; this header is the committed API.
 *
 * learnsets.h is NOT replaced. It answers one warn-level question — "could this
 * line ever learn this move by any Gen-3 method?" — by unioning the three game
 * groups, dropping the level, and accepting every TM/HM and tutor move for every
 * species. This header answers the four questions that union threw away:
 *
 *   WHICH source can teach the move (level-up / TM-HM / tutor / egg),
 *   AT WHAT LEVEL a level-up move is learned,
 *   IN WHICH game group, and
 *   WHETHER the answer is backed by real data or an approximation.
 *
 * The level is what makes the one move check that survives cross-game trading
 * possible: a move that is only ever a level-up move for the line, whose minimum
 * learn level exceeds the mon's current level, cannot be on that mon. The Move
 * Reminder only reteaches moves at or below the current level, and levels never
 * decrease. Every other move rule is defeated by trading (an RS-origin mon can
 * visit Emerald and pick up an Emerald tutor move), so per-game answers here are
 * building blocks: the checker is expected to UNION across game groups before
 * concluding anything, exactly as gen_legality.py does today.
 *
 * CODE-TAUGHT MOVES: four Gen-3 moves are handed out by a hand-written function
 * rather than a learnset table, and are folded in so they never come back as
 * "no source" — Frenzy Plant / Blast Burn / Hydro Cannon appear as FRLG tutor
 * moves for Venusaur / Charizard / Blastoise only (the Cape Brink tutor; Emerald
 * has no equivalent), and Volt Tackle appears as a Pichu egg move in Emerald and
 * FRLG but NOT in RS, whose daycare code cannot produce it.
 *
 * SPECIES vs LINE: every function here is per-species. Gen-3 mons keep the moves
 * they learned as a pre-evolution, so a caller checking a Charizard must also ask
 * about Charmeleon and Charmander. The pre-evolution table is not duplicated here
 * — it belongs to the encounter module (T_preevo) — so the caller walks the chain
 * and takes the minimum / union itself.
 *
 * Zero EWRAM: all tables are const and read in place (hard convention 2). */

/* Move-source bits. A set bit means "this method CAN supply the move to this
 * species in this game group" — not that it did. */
#define LG2_SRC_LEVELUP  0x01
#define LG2_SRC_TMHM     0x02
#define LG2_SRC_TUTOR    0x04
#define LG2_SRC_EGG      0x08
#define LG2_SRC_ALL      0x0F

/* Level-up entries are packed exactly as the games pack them
 * (LEVEL_UP_MOVE(level, move) == (level << 9) | move). */
#define LG2_LV_LEVEL(e)  ((int)((e) >> 9))
#define LG2_LV_MOVE(e)   ((uint16_t)((e) & 0x1FF))

typedef struct {
  uint8_t srcs;        /* LG2_SRC_* mask: methods that can supply the move       */
  uint8_t approx;      /* LG2_SRC_* mask: bits whose table was APPROXIMATED for  */
                       /* this game group — treat those answers as "maybe", not  */
                       /* as evidence of anything. See lg2_exact_sources().      */
  int16_t levelup_at;  /* lowest level-up level for the move, -1 if never level-up.
                        * Reported even when `level` gated LG2_SRC_LEVELUP off, so
                        * the caller can apply the level-window rule directly.    */
} Lg2Sources;

/* Which methods can teach `move` to `species` in game group `g`.
 *
 * `level` is the mon's CURRENT level: LG2_SRC_LEVELUP is set only if the move's
 * minimum learn level is at or below it. Pass 0 to ignore the level window and
 * get every source the species has. Returns the same mask as out->srcs (0 = no
 * known source, or bad arguments); `out` may be NULL. */
int lg2_move_sources(PkGame g, uint16_t species, uint16_t move, uint8_t level,
                     Lg2Sources* out);

/* Lowest level at which `species` learns `move` by level-up in `g`; -1 if it
 * never does. (A species can list a move twice — evolutions relearn theirs at
 * level 1 — so this is the minimum, not the first entry.) */
int lg2_min_levelup_level(PkGame g, uint16_t species, uint16_t move);

/* Raw list access, for the checker's "moves it could know at this level" pass and
 * for the UI. Returns the entry count and points *out at the const table itself
 * (never copied). Decode entries with LG2_LV_LEVEL / LG2_LV_MOVE; level-up
 * entries are in the games' own ascending-level order. */
int lg2_levelup_list(PkGame g, uint16_t species, const uint16_t** out);
int lg2_egg_list(PkGame g, uint16_t species, const uint16_t** out);

/* Per-species machine / tutor compatibility. */
bool lg2_tmhm(PkGame g, uint16_t species, uint16_t move);
bool lg2_tutor(PkGame g, uint16_t species, uint16_t move);

/* Is the move a TM/HM (or a tutor move) at all in Gen 3, and which one?
 * Returns 0-based ordinals — TM/HM in TM01..TM50, HM01..HM08 order, so 0 is TM01
 * and 50 is HM01 — or -1 if the move is not on that list. A "-1" here is what
 * tells the checker that a move is level-up/egg-only, which is the precondition
 * of the level-window rule. */
int lg2_tmhm_index(uint16_t move);
int lg2_tutor_index(uint16_t move);

/* Honesty accessors. Data availability differs per game group: the local pokeruby
 * checkout carries level-up and egg moves but no TM/HM or tutor compatibility, so
 * those two are approximated for PK_RS by OR-ing the game groups that ARE present
 * (a strictly wider answer, so it can never false-flag a legit mon — but it is
 * also not evidence). lg2_exact_sources() returns the LG2_SRC_* bits whose table
 * is real per-game data for `g`; anything missing from it must not be used to
 * conclude "illegal". Run tools/gen_learnsets2.py to see the provenance report. */
uint8_t lg2_exact_sources(PkGame g);

/* False when source/learnsets2.c was never generated and the weak fallbacks below
 * are answering. A caller MUST skip its move verdicts entirely in that case. */
bool lg2_have_data(void);

/* ---- weak no-data fallbacks ---------------------------------------------
 * source/learnsets2.c is generated and git-ignored, so a fresh clone that has not
 * run tools/gen_learnsets2.py has no tables at all. Same posture as
 * source/art_fallbacks.c: the build must still link and the product must still
 * behave, so every entry point gets a weak definition here and the generated file
 * (which defines LG2_STRONG_IMPL) overrides all of them at link time.
 *
 * The fallback answers are chosen to FAIL SAFE, i.e. towards "legal": TM/tutor/egg
 * are reported as possible for everything and no move is reported as level-up-only,
 * so none of the V2 move checks can fire. PokeDNA must never call a legit Pokemon
 * illegal because a build step was skipped. lg2_have_data() returns false so the
 * UI can say so out loud rather than silently showing green.
 *
 * These are function definitions in a header on purpose: they must exist without
 * adding a committed .c that would then be dead code in every real build. Multiple
 * including TUs each emit a weak copy, which the linker coalesces. */
#ifndef LG2_STRONG_IMPL

__attribute__((weak)) bool lg2_have_data(void) { return false; }
__attribute__((weak)) uint8_t lg2_exact_sources(PkGame g) { (void)g; return 0; }

__attribute__((weak)) int lg2_levelup_list(PkGame g, uint16_t s, const uint16_t** o) {
  (void)g; (void)s; if (o) *o = 0; return 0;
}
__attribute__((weak)) int lg2_egg_list(PkGame g, uint16_t s, const uint16_t** o) {
  (void)g; (void)s; if (o) *o = 0; return 0;
}
__attribute__((weak)) int lg2_min_levelup_level(PkGame g, uint16_t s, uint16_t m) {
  (void)g; (void)s; (void)m; return -1;
}
__attribute__((weak)) int lg2_tmhm_index(uint16_t m) { (void)m; return -1; }
__attribute__((weak)) int lg2_tutor_index(uint16_t m) { (void)m; return -1; }
__attribute__((weak)) bool lg2_tmhm(PkGame g, uint16_t s, uint16_t m) {
  (void)g; (void)s; return m != 0;
}
__attribute__((weak)) bool lg2_tutor(PkGame g, uint16_t s, uint16_t m) {
  (void)g; (void)s; return m != 0;
}
__attribute__((weak)) int lg2_move_sources(PkGame g, uint16_t s, uint16_t m,
                                           uint8_t lv, Lg2Sources* out) {
  Lg2Sources r;
  (void)g; (void)s; (void)lv;
  /* no LG2_SRC_LEVELUP: with levelup_at == -1 that bit would be self-contradictory,
   * and its absence is also what keeps the level-window rule from firing. */
  r.srcs = m ? (uint8_t)(LG2_SRC_TMHM | LG2_SRC_TUTOR | LG2_SRC_EGG) : 0;
  r.approx = LG2_SRC_ALL;
  r.levelup_at = -1;
  if (out) *out = r;
  return r.srcs;
}

#endif /* !LG2_STRONG_IMPL */

#endif /* LEARNSETS2_H */
