#ifndef MON_FRONT_INCLUDED
#define MON_FRONT_INCLUDED

#include <stdint.h>
#include <stdbool.h>

/* 64x64 front battle sprites (normal + shiny, LZ77-compressed in ROM,
 * Pixel format matches mon_icons: u16 per pixel, 0 = transparent, 0x8000|RGB15 =
 * opaque. Keyed by INTERNAL Gen-3 species id (same as mon_icon_for).
 *
 * The pixel data (source/mon_front.c + source/mon_front_data.s + data/*.bin) is
 * GENERATED by tools/gen_front.py and is git-ignored (ripped art). If absent,
 * mon_front_for() simply isn't linked; callers should fall back to mon_icon_for. */

#define MON_FRONT_W 64
#define MON_FRONT_H 64

/* Front sprite for an internal species id (normal or shiny), or NULL if none. */
const uint16_t* mon_front_for(uint16_t species, bool shiny);

/* Like mon_front_for, but picks the Unown letter sprite for species 201 using
 * `form` (0..27 = A..?); for every other species `form` is ignored. */
const uint16_t* mon_front_for_form(uint16_t species, bool shiny, uint8_t form);

#endif /* MON_FRONT_INCLUDED */
