/* Committed API header. The DATA (mon_icons_oam.c + blobs) is generated by
 * tools/gen_icons_oam.py and git-ignored; an art-free build links the weak
 * fallbacks in art_fallbacks.c (no icons, zero palettes). */
#ifndef MON_ICONS_OAM_INCLUDED
#define MON_ICONS_OAM_INCLUDED
#include <stdint.h>

#define MON_ICON_OAM_TILES   16   /* 4bpp tiles per 32x32 icon */
#define MON_ICON_OAM_TILE_BYTES 32
#define MON_ICON_OAM_BANKS   13   /* shared OBJ palette banks   */
#define MON_ICON_OAM_PALLEN  16   /* colours per bank           */
#define MON_ICON_OAM_SLOTS   417   /* distinct icons in the blob */

/* The 16 shared OBJ palettes (16 banks x 16 colours, slot 0 transparent),
   uploaded to OBJ PAL RAM once on box entry. */
extern const uint16_t mon_icon_oam_pal[MON_ICON_OAM_BANKS * MON_ICON_OAM_PALLEN];

/* For internal Gen-3 species id (Unown via the _form variant, letter 0..27):
   return 1 and set *tiles to the 16x32B 4bpp tile run and *bank to the icon's
   palette-bank index (0..15); return 0 if the species has no icon. */
int mon_icon_oam_for(uint16_t species, const uint8_t** tiles, int* bank);
int mon_icon_oam_for_form(uint16_t species, uint8_t form,
                          const uint8_t** tiles, int* bank);
/* frame 0/1 of the 2-frame bob (frame 1 tiles follow all frame-0 tiles in the blob). */
int mon_icon_oam_for_form_frame(uint16_t species, uint8_t form, uint8_t frame,
                                const uint8_t** tiles, int* bank);
/* The real Gen-3 Egg box icon; return 0 if absent. */
int mon_icon_oam_egg(const uint8_t** tiles, int* bank);

#endif
