/* Committed API header. The DATA (mon_icons.c + blobs) is generated by
 * tools/gen_icons.py and git-ignored; an art-free build links the weak NULL
 * fallbacks in art_fallbacks.c instead. */
#ifndef MON_ICONS_INCLUDED
#define MON_ICONS_INCLUDED
#include <stdint.h>
#include <stdbool.h>

struct RomMon;

#define MON_ICON_W 32
#define MON_ICON_H 32
#define MON_ICON_FRAMES 2
#define MON_ICON_MAX_SPECIES 411

/* 32x32 icon (RGB15: 0 transparent, 0x8000|rgb opaque) for an internal
   Gen-3 species id, or NULL if none. mon_icon_for* return frame 0; the
   *_frame variants pick animation frame 0/1 (the Gen-3 icon bob). */
const uint16_t* mon_icon_for(uint16_t species);
const uint16_t* mon_icon_for_frame(uint16_t species, uint8_t frame);
/* Like mon_icon_for, but the Unown letter `form` (0..27) for species 201. */
const uint16_t* mon_icon_for_form(uint16_t species, uint8_t form);
const uint16_t* mon_icon_for_form_frame(uint16_t species, uint8_t form, uint8_t frame);
/* The real Gen-3 Egg icon (32x32, 2 frames), or NULL if absent. */
const uint16_t* mon_icon_egg_frame(uint8_t frame);
const uint16_t* mon_icon_egg(void);

/* icons.bin-cache-backed fallback only (art_fallbacks.c): drop the small MRU cache
 * the fallback keeps over recently-read icon frames. Call whenever the file behind
 * icons.bin's path may have changed content (a ROM re-registration, a fresh
 * extraction) -- pdna_main.c's app_icon_cache_resolve is the one place that already
 * resets every other icons.bin-derived memo, so this joins that chokepoint. Always
 * defined (never weak), so it links in the full-art build too, where it is a no-op. */
void icon_frame_cache_invalidate(void);

/* Phase 1.5 (ROM rung below the icons.bin cache, art_fallbacks.c): register the
 * open RomMon these accessors should stream from once no cache is available. Call
 * from pdna_main.c's app_icon_rom_open(), right beside boxoam_rom_icons() -- same
 * open RomMon, a second independent reader. Pass NULL/not-ok to clear (no ROM this
 * session). Always defined (never weak), so it links in the full-art build too,
 * where it is a no-op (the weak accessors above are unreferenced there). */
void art_fallbacks_set_rommon(const struct RomMon* rm);

/* Is the icon source currently cheap enough to redraw on every idle-animation tick
 * (compiled art or the icons.bin cache), or must a caller keep showing a static
 * first frame because the only source is the ROM rung (real per-icon SD reads)?
 * See art_fallbacks.c's definition for the full "no SD I/O on an animation tick"
 * reasoning. Always defined (never weak); always true in the full-art build. */
bool mon_icon_anim_cheap(void);

#endif
