#ifndef MON_BACK_INCLUDED
#define MON_BACK_INCLUDED

#include <stdint.h>
#include <stdbool.h>

/* 64x64 BACK battle sprites (normal + shiny, LZ77-compressed in ROM), the
 * player's-side view shown by the summary's back-sprite toggle (issue #12).
 * Same pixel format as mon_front: u16 per pixel, 0 = transparent,
 * 0x8000|RGB15 = opaque. Keyed by INTERNAL Gen-3 species id.
 *
 * The pixel data (source/mon_back.c + source/mon_back_data.s + data/mon_back*.bin)
 * is GENERATED by tools/gen_back.py and is git-ignored (ripped art). If absent,
 * the build won't link mon_back_for(); callers fall back to the front sprite. */

#define MON_BACK_W 64
#define MON_BACK_H 64

/* Back sprite for an internal species id (normal or shiny), or NULL if none. */
const uint16_t* mon_back_for(uint16_t species, bool shiny);

/* Like mon_back_for, but picks the Unown letter sprite for species 201 using
 * `form` (0..27 = A..?); for every other species `form` is ignored. */
const uint16_t* mon_back_for_form(uint16_t species, bool shiny, uint8_t form);

#endif /* MON_BACK_INCLUDED */
