#ifndef MON_FRONT_INCLUDED
#define MON_FRONT_INCLUDED

#include <stdint.h>
#include <stdbool.h>

/* 48x48 front battle sprites (normal + shiny) for the summary / box data panel.
 * Pixel format matches mon_icons: u16 per pixel, 0 = transparent, 0x8000|RGB15 =
 * opaque. Keyed by INTERNAL Gen-3 species id (same as mon_icon_for).
 *
 * The pixel data (source/mon_front.c + source/mon_front_data.s + data/*.bin) is
 * GENERATED by tools/gen_front.py and is git-ignored (ripped art). If absent,
 * mon_front_for() simply isn't linked; callers should fall back to mon_icon_for. */

#define MON_FRONT_W 48
#define MON_FRONT_H 48

/* Front sprite for an internal species id (normal or shiny), or NULL if none. */
const uint16_t* mon_front_for(uint16_t species, bool shiny);

#endif /* MON_FRONT_INCLUDED */
