/* Committed API header. The DATA (mon_icons.c + blobs) is generated by
 * tools/gen_icons.py and git-ignored; an art-free build links the weak NULL
 * fallbacks in art_fallbacks.c instead. */
#ifndef MON_ICONS_INCLUDED
#define MON_ICONS_INCLUDED
#include <stdint.h>

#define MON_ICON_W 32
#define MON_ICON_H 32
#define MON_ICON_FRAMES 2
#define MON_ICON_MAX_SPECIES 411

/* 32x32 icon (RGB15: 0 transparent, 0x8000|rgb opaque) for an internal
   Gen-3 species id, or NULL if none. mon_icon_for* return frame 0; the
   *_frame variants pick animation frame 0/1 (the Gen-3 icon bob). */
const uint16_t* mon_icon_for(uint16_t species);
const uint16_t* mon_icon_for_frame(uint16_t species, uint8_t frame);
/* Like mon_icon_for, but the Unown letter `form` (0..27) for species 201. */
const uint16_t* mon_icon_for_form(uint16_t species, uint8_t form);
const uint16_t* mon_icon_for_form_frame(uint16_t species, uint8_t form, uint8_t frame);
/* The real Gen-3 Egg icon (32x32, 2 frames), or NULL if absent. */
const uint16_t* mon_icon_egg_frame(uint8_t frame);
const uint16_t* mon_icon_egg(void);

#endif
