/* GENERATED by tools/gen_pak.py - do not edit. */
#ifndef SPRITE_PAK_H
#define SPRITE_PAK_H
/* Base byte offsets of each blob within /PokeDNA/sprites.pak (trimmed SD build). */
#define PAK_FS_BASE 0x00000000u   /* front shiny */
#define PAK_BN_BASE 0x000e4eb4u   /* back normal */
#define PAK_BS_BASE 0x001a7bacu   /* back shiny  */
#endif
