/* Committed API header. The DATA (type_icons.c) is generated by
 * tools/gen_types.py and git-ignored; art-free builds get NULL from
 * art_fallbacks.c and draw original text type-chips instead. */
#ifndef TYPE_ICONS_INCLUDED
#define TYPE_ICONS_INCLUDED
#include <stdint.h>
#define TYPE_ICON_W 32
#define TYPE_ICON_H 14
#define TYPE_ICON_N 18
extern const uint16_t type_icons[TYPE_ICON_N * TYPE_ICON_W * TYPE_ICON_H];
/* &type_icons[t * W*H]; t = Gen-3 internal type id 0..17 (9 = unused). */
const uint16_t* type_icon_for(uint8_t t);
#endif
