#ifndef UI_FONT_H
#define UI_FONT_H

/* PokeDNA's own proportional 5x7 face, generated by tools/gen_font.py.
 *
 * The tool's default face is tonc's sys8: a FIXED 8 px cell whose glyphs already
 * ink 6 of those 8 columns. That is why every list truncated -- nine characters is
 * all a 76 px panel can hold at 8 px/glyph. The retail games do not have that
 * problem because their font is variable-width, which is how Emerald's own bag
 * prints `SUPER POTION` and `No01 FOCUS PUNCH` in the same space.
 *
 * Glyphs: ASCII 32..127, 8 bytes each, one byte per row, top row first.
 * Bit 0 of a row byte is the LEFTMOST pixel (the order tonc's sys8 uses too).
 * Rows 0..6 are the body with the baseline at row 6; row 7 carries descenders.
 * ui_font_w[i] is the ADVANCE in pixels: ink width + a 1 px inter-glyph gap. */

extern const unsigned char ui_font_bits[96 * 8];
extern const unsigned char ui_font_w[96];

#define UI_FONT_CELL_H 8    /* rows per glyph, so a proportional line still pitches at 8 */

#endif /* UI_FONT_H */
