#ifndef UI_FONT_H
#define UI_FONT_H

/* PokeDNA's own proportional 5x7 face, generated by tools/gen_font.py.
 *
 * The tool's default face is tonc's sys8: a FIXED 8 px cell whose glyphs already
 * ink 6 of those 8 columns. That is why every list truncated -- nine characters is
 * all a 76 px panel can hold at 8 px/glyph. The retail games do not have that
 * problem because their font is variable-width, which is how Emerald's own bag
 * prints `SUPER POTION` and `No01 FOCUS PUNCH` in the same space.
 *
 * Glyphs: ASCII 32..127, 8 bytes each, one byte per row, top row first.
 * Bit 0 of a row byte is the LEFTMOST pixel (the order tonc's sys8 uses too).
 * Rows 0..6 are the body with the baseline at row 6; row 7 carries descenders.
 * ui_font_w[i] is the ADVANCE in pixels: ink width + a 1 px inter-glyph gap. */

extern const unsigned char ui_font_bits[96 * 8];
extern const unsigned char ui_font_w[96];

#define UI_FONT_CELL_H 8    /* rows per glyph, so a proportional line still pitches at 8 */

/* TIGHT-SPACING delta (source/ui.c's ui_ptext_*_tight family; see the block comment
 * there for the full derivation). Party names ("SALAMENCE", "METAGROSS", ...) render
 * 54 px wide at the default 6 px/glyph advance -- our capital letters ink 5 of those 6
 * px, so even a ZERO-gap kerning (delta=1, i.e. touching but not overlapping) only saves
 * 1 px/glyph, and a 10-glyph name (the worst real case: a full-length species name or a
 * capped Gen-3 nickname) still runs 50 px against the party row's 48 px name column.
 * delta=2 is the smallest INTEGER delta that clears it -- it costs one column of genuine
 * ink overlap between adjacent glyphs (still no bitmap edit; a rendering choice, not a
 * font change) and leaves 8 px of slack on the worst case instead of overflowing by 2.
 * Defined here (not in ui.c) so tests/host_textfit_test.c, which links ui_font.c but
 * never ui.c, can mirror the exact same number rather than re-typing it -- the whole
 * point of this file's own "measures its own copy" rule (see host_textfit_test.c's
 * top-of-file comment). Used ONLY by the tight functions; every existing ui_ptext* call
 * is untouched and keeps its original per-glyph advance. */
#define UI_PTEXT_TIGHT_DELTA 2

#endif /* UI_FONT_H */
